//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.adapters.XmlAdapter;
import java.time.LocalDateTime;

public class Adapter1 extends XmlAdapter<String, LocalDateTime> {

  public LocalDateTime unmarshal(String value) {
    return (LocalDateTime.parse(value));
  }

  public String marshal(LocalDateTime value) {
    if (value == null) {
      return null;
    }
    return value.toString();
  }
}
