//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.AdditiveDetails;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for AdditiveDetails complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AdditiveDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="additiveLevelOfContainment" type="{}LevelOfContainmentCode"/>
 *         <element name="additiveName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditiveDetails", propOrder = {
    "additiveLevelOfContainment",
    "additiveName"
})
public class AdditiveDetailsXMLImpl implements AdditiveDetails {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected LevelOfContainmentCode additiveLevelOfContainment;
    @XmlElement(required = true)
    protected String additiveName;

    /**
     * Gets the value of the additiveLevelOfContainment property.
     * 
     * @return
     *     possible object is
     *     {@link LevelOfContainmentCode }
     *     
     */
    @Override
    public LevelOfContainmentCode getAdditiveLevelOfContainment() {
        return additiveLevelOfContainment;
    }

    /**
     * Sets the value of the additiveLevelOfContainment property.
     * 
     * @param value
     *     allowed object is
     *     {@link LevelOfContainmentCode }
     *     
     */
    @Override
    public void setAdditiveLevelOfContainment(LevelOfContainmentCode value) {
        this.additiveLevelOfContainment = value;
    }

    /**
     * Gets the value of the additiveName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getAdditiveName() {
        return additiveName;
    }

    /**
     * Sets the value of the additiveName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setAdditiveName(String value) {
        this.additiveName = value;
    }

}
