//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.AdditionalProductClassificationDetails;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * A product classification for the product other than the Global Product Classification(GPC brick value).
 *
 * <p>Java class for AdditionalProductClassificationDetails complex type</p>.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AdditionalProductClassificationDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="additionalProductClassificationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="additionalProductClassificationCodeDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="additionalProductClassificationValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdditionalProductClassificationDetails", propOrder = {
    "additionalProductClassificationCode",
    "additionalProductClassificationCodeDescription",
    "additionalProductClassificationValue"
})
public class AdditionalProductClassificationDetailsXMLImpl implements AdditionalProductClassificationDetails {

    @XmlElement(required = true)
    protected String additionalProductClassificationCode;
    @XmlElement(required = true)
    protected String additionalProductClassificationCodeDescription;
    @XmlElement(required = true)
    protected String additionalProductClassificationValue;

    /**
     * Gets the value of the additionalProductClassificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getAdditionalProductClassificationCode() {
        return additionalProductClassificationCode;
    }

    /**
     * Sets the value of the additionalProductClassificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setAdditionalProductClassificationCode(String value) {
        this.additionalProductClassificationCode = value;
    }

    /**
     * Gets the value of the additionalProductClassificationCodeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getAdditionalProductClassificationCodeDescription() {
        return additionalProductClassificationCodeDescription;
    }

    /**
     * Sets the value of the additionalProductClassificationCodeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setAdditionalProductClassificationCodeDescription(String value) {
        this.additionalProductClassificationCodeDescription = value;
    }

    /**
     * Gets the value of the additionalProductClassificationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getAdditionalProductClassificationValue() {
        return additionalProductClassificationValue;
    }

    /**
     * Sets the value of the additionalProductClassificationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setAdditionalProductClassificationValue(String value) {
        this.additionalProductClassificationValue = value;
    }

}
