//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Beverage complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Beverage">
 *   <complexContent>
 *     <extension base="{}FoodBeverageTobaccoProduct">
 *       <sequence>
 *         <element name="alcoholicBeverageSubregion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="beverageVintage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="isCarbonated" type="{}NonbinaryLogicCode"/>
 *         <element name="isDecaffeinated" type="{}NonbinaryLogicCode"/>
 *         <element name="isFromConcentrate" type="{}NonbinaryLogicCode"/>
 *         <element name="isVintage" type="{}NonbinaryLogicCode"/>
 *         <element name="percentageOfAlcoholByVolume" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="vintner" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Beverage", propOrder = {
    "alcoholicBeverageSubregion",
    "beverageVintage",
    "isCarbonated",
    "isDecaffeinated",
    "isFromConcentrate",
    "isVintage",
    "percentageOfAlcoholByVolume",
    "vintner"
})
public class Beverage
    extends FoodBeverageTobaccoProduct
{

    @XmlElement(required = true)
    protected String alcoholicBeverageSubregion;
    @XmlElement(required = true)
    protected String beverageVintage;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isCarbonated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isDecaffeinated;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isFromConcentrate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isVintage;
    @XmlElement(required = true)
    protected String percentageOfAlcoholByVolume;
    @XmlElement(required = true)
    protected String vintner;

    /**
     * Gets the value of the alcoholicBeverageSubregion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlcoholicBeverageSubregion() {
        return alcoholicBeverageSubregion;
    }

    /**
     * Sets the value of the alcoholicBeverageSubregion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlcoholicBeverageSubregion(String value) {
        this.alcoholicBeverageSubregion = value;
    }

    /**
     * Gets the value of the beverageVintage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeverageVintage() {
        return beverageVintage;
    }

    /**
     * Sets the value of the beverageVintage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeverageVintage(String value) {
        this.beverageVintage = value;
    }

    /**
     * Gets the value of the isCarbonated property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsCarbonated() {
        return isCarbonated;
    }

    /**
     * Sets the value of the isCarbonated property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsCarbonated(NonbinaryLogicCode value) {
        this.isCarbonated = value;
    }

    /**
     * Gets the value of the isDecaffeinated property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsDecaffeinated() {
        return isDecaffeinated;
    }

    /**
     * Sets the value of the isDecaffeinated property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsDecaffeinated(NonbinaryLogicCode value) {
        this.isDecaffeinated = value;
    }

    /**
     * Gets the value of the isFromConcentrate property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsFromConcentrate() {
        return isFromConcentrate;
    }

    /**
     * Sets the value of the isFromConcentrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsFromConcentrate(NonbinaryLogicCode value) {
        this.isFromConcentrate = value;
    }

    /**
     * Gets the value of the isVintage property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsVintage() {
        return isVintage;
    }

    /**
     * Sets the value of the isVintage property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsVintage(NonbinaryLogicCode value) {
        this.isVintage = value;
    }

    /**
     * Gets the value of the percentageOfAlcoholByVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageOfAlcoholByVolume() {
        return percentageOfAlcoholByVolume;
    }

    /**
     * Sets the value of the percentageOfAlcoholByVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageOfAlcoholByVolume(String value) {
        this.percentageOfAlcoholByVolume = value;
    }

    /**
     * Gets the value of the vintner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVintner() {
        return vintner;
    }

    /**
     * Sets the value of the vintner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVintner(String value) {
        this.vintner = value;
    }

}
