//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for CheeseFirmnessCode</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CheeseFirmnessCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="EXTRA_HARD"/>
 *     <enumeration value="FIRM_SEMIHARD"/>
 *     <enumeration value="HARD"/>
 *     <enumeration value="SOFT"/>
 *     <enumeration value="UNIDENTIFIED"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CheeseFirmnessCode")
@XmlEnum
public enum CheeseFirmnessCode {

    EXTRA_HARD,
    FIRM_SEMIHARD,
    HARD,
    SOFT,
    UNIDENTIFIED;

    public String value() {
        return name();
    }

    public static CheeseFirmnessCode fromValue(String v) {
        return valueOf(v);
    }

}
