/*
 * Copyright 2022-2026 benelog GmbH & Co. KG
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.Country;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Country is a complex data type that indicates a country and a country subdivision.
 *
 * <p>Java class for Country complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="Country">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="countrySubdivisionCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Country",
    propOrder = {"countryCode", "countrySubdivisionCode"})
public class CountryXMLImpl implements Country {

  @XmlElement(required = true)
  protected String countryCode;

  @XmlElement(required = true)
  protected String countrySubdivisionCode;

  /**
   * Gets the value of the countryCode property.
   *
   * @return possible object is {@link String }
   */
  @Override
  public String getCountryCode() {
    return countryCode;
  }

  /**
   * Sets the value of the countryCode property.
   *
   * @param value allowed object is {@link String }
   */
  @Override
  public void setCountryCode(String value) {
    this.countryCode = value;
  }

  /**
   * Gets the value of the countrySubdivisionCode property.
   *
   * @return possible object is {@link String }
   */
  @Override
  public String getCountrySubdivisionCode() {
    return countrySubdivisionCode;
  }

  /**
   * Sets the value of the countrySubdivisionCode property.
   *
   * @param value allowed object is {@link String }
   */
  @Override
  public void setCountrySubdivisionCode(String value) {
    this.countrySubdivisionCode = value;
  }
}
