//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DietTypeCodeDetails complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DietTypeCodeDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="dietType" type="{}DietTypeCode"/>
 *         <element name="dietTypeSubcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DietTypeCodeDetails", propOrder = {
    "dietType",
    "dietTypeSubcode"
})
public class DietTypeCodeDetails {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected DietTypeCode dietType;
    @XmlElement(required = true)
    protected String dietTypeSubcode;

    /**
     * Gets the value of the dietType property.
     * 
     * @return
     *     possible object is
     *     {@link DietTypeCode }
     *     
     */
    public DietTypeCode getDietType() {
        return dietType;
    }

    /**
     * Sets the value of the dietType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DietTypeCode }
     *     
     */
    public void setDietType(DietTypeCode value) {
        this.dietType = value;
    }

    /**
     * Gets the value of the dietTypeSubcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDietTypeSubcode() {
        return dietTypeSubcode;
    }

    /**
     * Sets the value of the dietTypeSubcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDietTypeSubcode(String value) {
        this.dietTypeSubcode = value;
    }

}
