//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for FruitsVegetables complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FruitsVegetables">
 *   <complexContent>
 *     <extension base="{}FoodBeverageTobaccoProduct">
 *       <sequence>
 *         <element name="isPittedStoned" type="{}NonbinaryLogicCode"/>
 *         <element name="isSeedless" type="{}NonbinaryLogicCode"/>
 *         <element name="isShelledPeeled" type="{}NonbinaryLogicCode"/>
 *         <element name="isWashedReadyToEat" type="{}NonbinaryLogicCode"/>
 *         <element name="maturationMethod" type="{}MaturationMethodCode"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FruitsVegetables", propOrder = {
    "isPittedStoned",
    "isSeedless",
    "isShelledPeeled",
    "isWashedReadyToEat",
    "maturationMethod"
})
public class FruitsVegetables
    extends FoodBeverageTobaccoProduct
{

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isPittedStoned;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isSeedless;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isShelledPeeled;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected NonbinaryLogicCode isWashedReadyToEat;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected MaturationMethodCode maturationMethod;

    /**
     * Gets the value of the isPittedStoned property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsPittedStoned() {
        return isPittedStoned;
    }

    /**
     * Sets the value of the isPittedStoned property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsPittedStoned(NonbinaryLogicCode value) {
        this.isPittedStoned = value;
    }

    /**
     * Gets the value of the isSeedless property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsSeedless() {
        return isSeedless;
    }

    /**
     * Sets the value of the isSeedless property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsSeedless(NonbinaryLogicCode value) {
        this.isSeedless = value;
    }

    /**
     * Gets the value of the isShelledPeeled property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsShelledPeeled() {
        return isShelledPeeled;
    }

    /**
     * Sets the value of the isShelledPeeled property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsShelledPeeled(NonbinaryLogicCode value) {
        this.isShelledPeeled = value;
    }

    /**
     * Gets the value of the isWashedReadyToEat property.
     * 
     * @return
     *     possible object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public NonbinaryLogicCode getIsWashedReadyToEat() {
        return isWashedReadyToEat;
    }

    /**
     * Sets the value of the isWashedReadyToEat property.
     * 
     * @param value
     *     allowed object is
     *     {@link NonbinaryLogicCode }
     *     
     */
    public void setIsWashedReadyToEat(NonbinaryLogicCode value) {
        this.isWashedReadyToEat = value;
    }

    /**
     * Gets the value of the maturationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link MaturationMethodCode }
     *     
     */
    public MaturationMethodCode getMaturationMethod() {
        return maturationMethod;
    }

    /**
     * Sets the value of the maturationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaturationMethodCode }
     *     
     */
    public void setMaturationMethod(MaturationMethodCode value) {
        this.maturationMethod = value;
    }

}
