/*
 * Copyright 2022-2026 benelog GmbH & Co. KG
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for GrowingMethodCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="GrowingMethodCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CAGE_FREE"/>
 *     <enumeration value="CLONED_FOODS"/>
 *     <enumeration value="CONVENTIONAL"/>
 *     <enumeration value="FARM_RAISED"/>
 *     <enumeration value="FIELD_GROWN"/>
 *     <enumeration value="FLY_FREE"/>
 *     <enumeration value="FREE_RANGE"/>
 *     <enumeration value="GRASS_FED"/>
 *     <enumeration value="GREENHOUSE"/>
 *     <enumeration value="HUMANELY_RAISED"/>
 *     <enumeration value="HYDROPONIC"/>
 *     <enumeration value="INTEGRATED_PEST_MANAGEMENT"/>
 *     <enumeration value="ORGANIC"/>
 *     <enumeration value="SHADE_GROWN"/>
 *     <enumeration value="SUSTAINABLE"/>
 *     <enumeration value="WILD"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "GrowingMethodCode")
@XmlEnum
public enum GrowingMethodCode {
  CAGE_FREE,
  CLONED_FOODS,
  CONVENTIONAL,
  FARM_RAISED,
  FIELD_GROWN,
  FLY_FREE,
  FREE_RANGE,
  GRASS_FED,
  GREENHOUSE,
  HUMANELY_RAISED,
  HYDROPONIC,
  INTEGRATED_PEST_MANAGEMENT,
  ORGANIC,
  SHADE_GROWN,
  SUSTAINABLE,
  WILD;

  public String value() {
    return name();
  }

  public static GrowingMethodCode fromValue(String v) {
    return valueOf(v);
  }
}
