//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for LocationID_Type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="LocationID_Type">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BIC_FACILITY"/>
 *     <enumeration value="CRD_LOCATION_CODE"/>
 *     <enumeration value="ENI_NUMBER"/>
 *     <enumeration value="FR_SIRET"/>
 *     <enumeration value="IATA_CODE"/>
 *     <enumeration value="IMO_NUMBER"/>
 *     <enumeration value="ISPS_CODE"/>
 *     <enumeration value="ISRS_LOCATION_CODE"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_1"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_10"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_2"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_3"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_4"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_5"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_6"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_7"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_8"/>
 *     <enumeration value="LOCATION_FOR_INTERNAL_USE_9"/>
 *     <enumeration value="MMSI_NUMBER"/>
 *     <enumeration value="OAR_ID"/>
 *     <enumeration value="OPEN_LOCATION_CODE"/>
 *     <enumeration value="SMDG_CODE"/>
 *     <enumeration value="UN_LOCODE"/>
 *     <enumeration value="US_CIF_CODE"/>
 *     <enumeration value="US_EST_NUMBER"/>
 *     <enumeration value="US_FEI"/>
 *     <enumeration value="US_HIN_IDENTIFICATION"/>
 *     <enumeration value="US_MINE_ID"/>
 *     <enumeration value="US_TCN_CODE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "LocationID_Type")
@XmlEnum
public enum LocationIDType {

    BIC_FACILITY,
    CRD_LOCATION_CODE,
    ENI_NUMBER,
    FR_SIRET,
    IATA_CODE,
    IMO_NUMBER,
    ISPS_CODE,
    ISRS_LOCATION_CODE,
    LOCATION_FOR_INTERNAL_USE_1,
    LOCATION_FOR_INTERNAL_USE_10,
    LOCATION_FOR_INTERNAL_USE_2,
    LOCATION_FOR_INTERNAL_USE_3,
    LOCATION_FOR_INTERNAL_USE_4,
    LOCATION_FOR_INTERNAL_USE_5,
    LOCATION_FOR_INTERNAL_USE_6,
    LOCATION_FOR_INTERNAL_USE_7,
    LOCATION_FOR_INTERNAL_USE_8,
    LOCATION_FOR_INTERNAL_USE_9,
    MMSI_NUMBER,
    OAR_ID,
    OPEN_LOCATION_CODE,
    SMDG_CODE,
    UN_LOCODE,
    US_CIF_CODE,
    US_EST_NUMBER,
    US_FEI,
    US_HIN_IDENTIFICATION,
    US_MINE_ID,
    US_TCN_CODE;

    public String value() {
        return name();
    }

    public static LocationIDType fromValue(String v) {
        return valueOf(v);
    }

}
