/*
 * Copyright 2022-2026 benelog GmbH & Co. KG
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.MeatPoultry;
import jakarta.xml.bind.annotation.*;

import java.util.LinkedHashMap;

/**
 * Meat and poultry products.
 *
 * <p>Java class for MeatPoultry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="MeatPoultry">
 *   <complexContent>
 *     <extension base="{}FoodBeverageTobaccoProduct">
 *       <sequence>
 *         <element name="anatomicalForm" type="{}AnatomicalFormCode"/>
 *         <element name="bonelessClaim" type="{}NonbinaryLogicCode"/>
 *         <element name="meatPoultryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="minimumMeatPoultryContent" type="{}QuantitativeValue"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "MeatPoultry",
    propOrder = {"anatomicalForm", "bonelessClaim", "meatPoultryType", "minimumMeatPoultryContent"})
public class MeatPoultryXMLImpl extends FoodBeverageTobaccoProductXMLImpl implements MeatPoultry<QuantitativeValueXMLImpl> {

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected AnatomicalFormCode anatomicalForm;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected NonbinaryLogicCode bonelessClaim;

  @XmlElement(required = true)
  protected LinkedHashMap<String, String> meatPoultryType;

  @XmlElement(required = true)
  protected QuantitativeValueXMLImpl minimumMeatPoultryContent;

  /**
   * Gets the value of the anatomicalForm property.
   *
   * @return possible object is {@link AnatomicalFormCode }
   */
  @Override
  public AnatomicalFormCode getAnatomicalForm() {
    return anatomicalForm;
  }

  /**
   * Sets the value of the anatomicalForm property.
   *
   * @param value allowed object is {@link AnatomicalFormCode }
   */
  @Override
  public void setAnatomicalForm(AnatomicalFormCode value) {
    this.anatomicalForm = value;
  }

  /**
   * Gets the value of the bonelessClaim property.
   *
   * @return possible object is {@link NonbinaryLogicCode }
   */
  @Override
  public NonbinaryLogicCode getBonelessClaim() {
    return bonelessClaim;
  }

  /**
   * Sets the value of the bonelessClaim property.
   *
   * @param value allowed object is {@link NonbinaryLogicCode }
   */
  @Override
  public void setBonelessClaim(NonbinaryLogicCode value) {
    this.bonelessClaim = value;
  }

  /**
   * Gets the value of the meatPoultryType property.
   *
   * @return possible object is {@link String }
   */
  @Override
  public LinkedHashMap<String, String> getMeatPoultryType() {
    if (meatPoultryType == null) {
      meatPoultryType = new LinkedHashMap<>();
    }
    return meatPoultryType;
  }

  /**
   * Sets the value of the meatPoultryType property.
   *
   * @param value allowed object is {@link String }
   */
  @Override
  public void setMeatPoultryType(LinkedHashMap<String, String> value) {
    this.meatPoultryType = value;
  }

  /**
   * Gets the value of the minimumMeatPoultryContent property.
   *
   * @return possible object is {@link QuantitativeValueXMLImpl }
   */
  @Override
  public QuantitativeValueXMLImpl getMinimumMeatPoultryContent() {
    return minimumMeatPoultryContent;
  }

  /**
   * Sets the value of the minimumMeatPoultryContent property.
   *
   * @param value allowed object is {@link QuantitativeValueXMLImpl }
   */
  @Override
  public void setMinimumMeatPoultryContent(QuantitativeValueXMLImpl value) {
    this.minimumMeatPoultryContent = value;
  }
}
