//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.openepcis.model.gs1webvocab package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.openepcis.model.gs1webvocab
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdditionalProductClassificationDetails }
     * 
     * @return
     *     the new instance of {@link AdditionalProductClassificationDetails }
     */
    public AdditionalProductClassificationDetails createAdditionalProductClassificationDetails() {
        return new AdditionalProductClassificationDetails();
    }

    /**
     * Create an instance of {@link AdditiveDetails }
     * 
     * @return
     *     the new instance of {@link AdditiveDetails }
     */
    public AdditiveDetails createAdditiveDetails() {
        return new AdditiveDetails();
    }

    /**
     * Create an instance of {@link AllergenDetails }
     * 
     * @return
     *     the new instance of {@link AllergenDetails }
     */
    public AllergenDetails createAllergenDetails() {
        return new AllergenDetails();
    }

    /**
     * Create an instance of {@link AuthenticityDetails }
     * 
     * @return
     *     the new instance of {@link AuthenticityDetails }
     */
    public AuthenticityDetails createAuthenticityDetails() {
        return new AuthenticityDetails();
    }

    /**
     * Create an instance of {@link AwardPrizeDetails }
     * 
     * @return
     *     the new instance of {@link AwardPrizeDetails }
     */
    public AwardPrizeDetails createAwardPrizeDetails() {
        return new AwardPrizeDetails();
    }

    /**
     * Create an instance of {@link Beverage }
     * 
     * @return
     *     the new instance of {@link Beverage }
     */
    public Beverage createBeverage() {
        return new Beverage();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     * @return
     *     the new instance of {@link Brand }
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link CertificationDetails }
     * 
     * @return
     *     the new instance of {@link CertificationDetails }
     */
    public CertificationDetails createCertificationDetails() {
        return new CertificationDetails();
    }

    /**
     * Create an instance of {@link Clothing }
     * 
     * @return
     *     the new instance of {@link Clothing }
     */
    public Clothing createClothing() {
        return new Clothing();
    }

    /**
     * Create an instance of {@link ColourCodeDetails }
     * 
     * @return
     *     the new instance of {@link ColourCodeDetails }
     */
    public ColourCodeDetails createColourCodeDetails() {
        return new ColourCodeDetails();
    }

    /**
     * Create an instance of {@link ContactPoint }
     * 
     * @return
     *     the new instance of {@link ContactPoint }
     */
    public ContactPoint createContactPoint() {
        return new ContactPoint();
    }

    /**
     * Create an instance of {@link Country }
     * 
     * @return
     *     the new instance of {@link Country }
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link DietTypeCodeDetails }
     * 
     * @return
     *     the new instance of {@link DietTypeCodeDetails }
     */
    public DietTypeCodeDetails createDietTypeCodeDetails() {
        return new DietTypeCodeDetails();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     * @return
     *     the new instance of {@link Discount }
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link FoodAndBeveragePreparationInformation }
     * 
     * @return
     *     the new instance of {@link FoodAndBeveragePreparationInformation }
     */
    public FoodAndBeveragePreparationInformation createFoodAndBeveragePreparationInformation() {
        return new FoodAndBeveragePreparationInformation();
    }

    /**
     * Create an instance of {@link FoodBeverageTobaccoIngredientDetails }
     * 
     * @return
     *     the new instance of {@link FoodBeverageTobaccoIngredientDetails }
     */
    public FoodBeverageTobaccoIngredientDetails createFoodBeverageTobaccoIngredientDetails() {
        return new FoodBeverageTobaccoIngredientDetails();
    }

    /**
     * Create an instance of {@link FoodBeverageTobaccoProduct }
     * 
     * @return
     *     the new instance of {@link FoodBeverageTobaccoProduct }
     */
    public FoodBeverageTobaccoProduct createFoodBeverageTobaccoProduct() {
        return new FoodBeverageTobaccoProduct();
    }

    /**
     * Create an instance of {@link Footwear }
     * 
     * @return
     *     the new instance of {@link Footwear }
     */
    public Footwear createFootwear() {
        return new Footwear();
    }

    /**
     * Create an instance of {@link FruitsVegetables }
     * 
     * @return
     *     the new instance of {@link FruitsVegetables }
     */
    public FruitsVegetables createFruitsVegetables() {
        return new FruitsVegetables();
    }

    /**
     * Create an instance of {@link GeoCoordinates }
     * 
     * @return
     *     the new instance of {@link GeoCoordinates }
     */
    public GeoCoordinates createGeoCoordinates() {
        return new GeoCoordinates();
    }

    /**
     * Create an instance of {@link GeoShape }
     * 
     * @return
     *     the new instance of {@link GeoShape }
     */
    public GeoShape createGeoShape() {
        return new GeoShape();
    }

    /**
     * Create an instance of {@link LocationIDDetails }
     * 
     * @return
     *     the new instance of {@link LocationIDDetails }
     */
    public LocationIDDetails createLocationIDDetails() {
        return new LocationIDDetails();
    }

    /**
     * Create an instance of {@link LocationStatusHistory }
     * 
     * @return
     *     the new instance of {@link LocationStatusHistory }
     */
    public LocationStatusHistory createLocationStatusHistory() {
        return new LocationStatusHistory();
    }

    /**
     * Create an instance of {@link MeatPoultry }
     * 
     * @return
     *     the new instance of {@link MeatPoultry }
     */
    public MeatPoultry createMeatPoultry() {
        return new MeatPoultry();
    }

    /**
     * Create an instance of {@link MilkButterCreamYogurtCheeseEggsSubstitutes }
     * 
     * @return
     *     the new instance of {@link MilkButterCreamYogurtCheeseEggsSubstitutes }
     */
    public MilkButterCreamYogurtCheeseEggsSubstitutes createMilkButterCreamYogurtCheeseEggsSubstitutes() {
        return new MilkButterCreamYogurtCheeseEggsSubstitutes();
    }

    /**
     * Create an instance of {@link NutritionMeasurementType }
     * 
     * @return
     *     the new instance of {@link NutritionMeasurementType }
     */
    public NutritionMeasurementType createNutritionMeasurementType() {
        return new NutritionMeasurementType();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     * @return
     *     the new instance of {@link Offer }
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link OrganicClaimDetails }
     * 
     * @return
     *     the new instance of {@link OrganicClaimDetails }
     */
    public OrganicClaimDetails createOrganicClaimDetails() {
        return new OrganicClaimDetails();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     * @return
     *     the new instance of {@link Organization }
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link OrganizationIDDetails }
     * 
     * @return
     *     the new instance of {@link OrganizationIDDetails }
     */
    public OrganizationIDDetails createOrganizationIDDetails() {
        return new OrganizationIDDetails();
    }

    /**
     * Create an instance of {@link OrganizationStatusHistory }
     * 
     * @return
     *     the new instance of {@link OrganizationStatusHistory }
     */
    public OrganizationStatusHistory createOrganizationStatusHistory() {
        return new OrganizationStatusHistory();
    }

    /**
     * Create an instance of {@link PackagingDetails }
     * 
     * @return
     *     the new instance of {@link PackagingDetails }
     */
    public PackagingDetails createPackagingDetails() {
        return new PackagingDetails();
    }

    /**
     * Create an instance of {@link PackagingMaterialDetails }
     * 
     * @return
     *     the new instance of {@link PackagingMaterialDetails }
     */
    public PackagingMaterialDetails createPackagingMaterialDetails() {
        return new PackagingMaterialDetails();
    }

    /**
     * Create an instance of {@link Place }
     * 
     * @return
     *     the new instance of {@link Place }
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link PostalAddress }
     * 
     * @return
     *     the new instance of {@link PostalAddress }
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link PriceSpecification }
     * 
     * @return
     *     the new instance of {@link PriceSpecification }
     */
    public PriceSpecification createPriceSpecification() {
        return new PriceSpecification();
    }

    /**
     * Create an instance of {@link Product }
     * 
     * @return
     *     the new instance of {@link Product }
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link ProductYieldDetails }
     * 
     * @return
     *     the new instance of {@link ProductYieldDetails }
     */
    public ProductYieldDetails createProductYieldDetails() {
        return new ProductYieldDetails();
    }

    /**
     * Create an instance of {@link QuantitativeValue }
     * 
     * @return
     *     the new instance of {@link QuantitativeValue }
     */
    public QuantitativeValue createQuantitativeValue() {
        return new QuantitativeValue();
    }

    /**
     * Create an instance of {@link ReferencedFileDetails }
     * 
     * @return
     *     the new instance of {@link ReferencedFileDetails }
     */
    public ReferencedFileDetails createReferencedFileDetails() {
        return new ReferencedFileDetails();
    }

    /**
     * Create an instance of {@link ReturnablePackageDepositDetails }
     * 
     * @return
     *     the new instance of {@link ReturnablePackageDepositDetails }
     */
    public ReturnablePackageDepositDetails createReturnablePackageDepositDetails() {
        return new ReturnablePackageDepositDetails();
    }

    /**
     * Create an instance of {@link Seafood }
     * 
     * @return
     *     the new instance of {@link Seafood }
     */
    public Seafood createSeafood() {
        return new Seafood();
    }

    /**
     * Create an instance of {@link SizeCodeDetails }
     * 
     * @return
     *     the new instance of {@link SizeCodeDetails }
     */
    public SizeCodeDetails createSizeCodeDetails() {
        return new SizeCodeDetails();
    }

    /**
     * Create an instance of {@link SizeDetails }
     * 
     * @return
     *     the new instance of {@link SizeDetails }
     */
    public SizeDetails createSizeDetails() {
        return new SizeDetails();
    }

    /**
     * Create an instance of {@link TargetMarketDetails }
     * 
     * @return
     *     the new instance of {@link TargetMarketDetails }
     */
    public TargetMarketDetails createTargetMarketDetails() {
        return new TargetMarketDetails();
    }

    /**
     * Create an instance of {@link TextileMaterialDetails }
     * 
     * @return
     *     the new instance of {@link TextileMaterialDetails }
     */
    public TextileMaterialDetails createTextileMaterialDetails() {
        return new TextileMaterialDetails();
    }

    /**
     * Create an instance of {@link TypeCode }
     * 
     * @return
     *     the new instance of {@link TypeCode }
     */
    public TypeCode createTypeCode() {
        return new TypeCode();
    }

    /**
     * Create an instance of {@link WarrantyPromise }
     * 
     * @return
     *     the new instance of {@link WarrantyPromise }
     */
    public WarrantyPromise createWarrantyPromise() {
        return new WarrantyPromise();
    }

    /**
     * Create an instance of {@link WearableProduct }
     * 
     * @return
     *     the new instance of {@link WearableProduct }
     */
    public WearableProduct createWearableProduct() {
        return new WearableProduct();
    }

    /**
     * Create an instance of {@link Thing }
     * 
     * @return
     *     the new instance of {@link Thing }
     */
    public Thing createThing() {
        return new Thing();
    }

}
