//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.openepcis.model.gs1webvocab package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ActivityIdeas_QNAME = new QName("", "activityIdeas");
    private static final QName _AllergenInfo_QNAME = new QName("", "allergenInfo");
    private static final QName _AppDownload_QNAME = new QName("", "appDownload");
    private static final QName _BrandHomepageClinical_QNAME = new QName("", "brandHomepageClinical");
    private static final QName _BrandHomepagePatient_QNAME = new QName("", "brandHomepagePatient");
    private static final QName _CareersInfo_QNAME = new QName("", "careersInfo");
    private static final QName _CertificationInfo_QNAME = new QName("", "certificationInfo");
    private static final QName _ConsumerHandlingStorageInfo_QNAME = new QName("", "consumerHandlingStorageInfo");
    private static final QName _DefaultLink_QNAME = new QName("", "defaultLink");
    private static final QName _DefaultLinkMulti_QNAME = new QName("", "defaultLinkMulti");
    private static final QName _Epcis_QNAME = new QName("", "epcis");
    private static final QName _Epil_QNAME = new QName("", "epil");
    private static final QName _EventsInfo_QNAME = new QName("", "eventsInfo");
    private static final QName _Faqs_QNAME = new QName("", "faqs");
    private static final QName _HandledBy_QNAME = new QName("", "handledBy");
    private static final QName _HasRetailers_QNAME = new QName("", "hasRetailers");
    private static final QName _Homepage_QNAME = new QName("", "homepage");
    private static final QName _IngredientsInfo_QNAME = new QName("", "ingredientsInfo");
    private static final QName _Instructions_QNAME = new QName("", "instructions");
    private static final QName _Jws_QNAME = new QName("", "jws");
    private static final QName _LeaveReview_QNAME = new QName("", "leaveReview");
    private static final QName _LocationInfo_QNAME = new QName("", "locationInfo");
    private static final QName _LogisticsInfo_QNAME = new QName("", "logisticsInfo");
    private static final QName _LoyaltyProgram_QNAME = new QName("", "loyaltyProgram");
    private static final QName _MasterData_QNAME = new QName("", "masterData");
    private static final QName _MenuInfo_QNAME = new QName("", "menuInfo");
    private static final QName _NutritionalInfo_QNAME = new QName("", "nutritionalInfo");
    private static final QName _OpeningHoursInfo_QNAME = new QName("", "openingHoursInfo");
    private static final QName _PaymentLink_QNAME = new QName("", "paymentLink");
    private static final QName _Pip_QNAME = new QName("", "pip");
    private static final QName _ProductSustainabilityInfo_QNAME = new QName("", "productSustainabilityInfo");
    private static final QName _Promotion_QNAME = new QName("", "promotion");
    private static final QName _PurchaseSuppliesOrAccessories_QNAME = new QName("", "purchaseSuppliesOrAccessories");
    private static final QName _QuickStartGuide_QNAME = new QName("", "quickStartGuide");
    private static final QName _RecallStatus_QNAME = new QName("", "recallStatus");
    private static final QName _RecipeInfo_QNAME = new QName("", "recipeInfo");
    private static final QName _RegisterProduct_QNAME = new QName("", "registerProduct");
    private static final QName _RegistryEntry_QNAME = new QName("", "registryEntry");
    private static final QName _RelatedImage_QNAME = new QName("", "relatedImage");
    private static final QName _RelatedVideo_QNAME = new QName("", "relatedVideo");
    private static final QName _Review_QNAME = new QName("", "review");
    private static final QName _SafetyInfo_QNAME = new QName("", "safetyInfo");
    private static final QName _ScheduleTime_QNAME = new QName("", "scheduleTime");
    private static final QName _ServiceInfo_QNAME = new QName("", "serviceInfo");
    private static final QName _SmartLabel_QNAME = new QName("", "smartLabel");
    private static final QName _Smpc_QNAME = new QName("", "smpc");
    private static final QName _SocialMedia_QNAME = new QName("", "socialMedia");
    private static final QName _StatisticInfo_QNAME = new QName("", "statisticInfo");
    private static final QName _Subscribe_QNAME = new QName("", "subscribe");
    private static final QName _Support_QNAME = new QName("", "support");
    private static final QName _SustainabilityInfo_QNAME = new QName("", "sustainabilityInfo");
    private static final QName _Traceability_QNAME = new QName("", "traceability");
    private static final QName _Tutorial_QNAME = new QName("", "tutorial");
    private static final QName _UserAgreement_QNAME = new QName("", "userAgreement");
    private static final QName _VerificationService_QNAME = new QName("", "verificationService");
    private static final QName _WhatsInTheBox_QNAME = new QName("", "whatsInTheBox");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.openepcis.model.gs1webvocab
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdditionalProductClassificationDetails }
     * 
     * @return
     *     the new instance of {@link AdditionalProductClassificationDetails }
     */
    public AdditionalProductClassificationDetails createAdditionalProductClassificationDetails() {
        return new AdditionalProductClassificationDetails();
    }

    /**
     * Create an instance of {@link AdditiveDetails }
     * 
     * @return
     *     the new instance of {@link AdditiveDetails }
     */
    public AdditiveDetails createAdditiveDetails() {
        return new AdditiveDetails();
    }

    /**
     * Create an instance of {@link AllergenDetails }
     * 
     * @return
     *     the new instance of {@link AllergenDetails }
     */
    public AllergenDetails createAllergenDetails() {
        return new AllergenDetails();
    }

    /**
     * Create an instance of {@link AuthenticityDetails }
     * 
     * @return
     *     the new instance of {@link AuthenticityDetails }
     */
    public AuthenticityDetails createAuthenticityDetails() {
        return new AuthenticityDetails();
    }

    /**
     * Create an instance of {@link AwardPrizeDetails }
     * 
     * @return
     *     the new instance of {@link AwardPrizeDetails }
     */
    public AwardPrizeDetails createAwardPrizeDetails() {
        return new AwardPrizeDetails();
    }

    /**
     * Create an instance of {@link Beverage }
     * 
     * @return
     *     the new instance of {@link Beverage }
     */
    public Beverage createBeverage() {
        return new Beverage();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     * @return
     *     the new instance of {@link Brand }
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link CertificationDetails }
     * 
     * @return
     *     the new instance of {@link CertificationDetails }
     */
    public CertificationDetails createCertificationDetails() {
        return new CertificationDetails();
    }

    /**
     * Create an instance of {@link Clothing }
     * 
     * @return
     *     the new instance of {@link Clothing }
     */
    public Clothing createClothing() {
        return new Clothing();
    }

    /**
     * Create an instance of {@link ColourCodeDetails }
     * 
     * @return
     *     the new instance of {@link ColourCodeDetails }
     */
    public ColourCodeDetails createColourCodeDetails() {
        return new ColourCodeDetails();
    }

    /**
     * Create an instance of {@link ContactPoint }
     * 
     * @return
     *     the new instance of {@link ContactPoint }
     */
    public ContactPoint createContactPoint() {
        return new ContactPoint();
    }

    /**
     * Create an instance of {@link Country }
     * 
     * @return
     *     the new instance of {@link Country }
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link DietTypeCodeDetails }
     * 
     * @return
     *     the new instance of {@link DietTypeCodeDetails }
     */
    public DietTypeCodeDetails createDietTypeCodeDetails() {
        return new DietTypeCodeDetails();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     * @return
     *     the new instance of {@link Discount }
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link FoodAndBeveragePreparationInformation }
     * 
     * @return
     *     the new instance of {@link FoodAndBeveragePreparationInformation }
     */
    public FoodAndBeveragePreparationInformation createFoodAndBeveragePreparationInformation() {
        return new FoodAndBeveragePreparationInformation();
    }

    /**
     * Create an instance of {@link FoodBeverageTobaccoIngredientDetails }
     * 
     * @return
     *     the new instance of {@link FoodBeverageTobaccoIngredientDetails }
     */
    public FoodBeverageTobaccoIngredientDetails createFoodBeverageTobaccoIngredientDetails() {
        return new FoodBeverageTobaccoIngredientDetails();
    }

    /**
     * Create an instance of {@link FoodBeverageTobaccoProduct }
     * 
     * @return
     *     the new instance of {@link FoodBeverageTobaccoProduct }
     */
    public FoodBeverageTobaccoProduct createFoodBeverageTobaccoProduct() {
        return new FoodBeverageTobaccoProduct();
    }

    /**
     * Create an instance of {@link Footwear }
     * 
     * @return
     *     the new instance of {@link Footwear }
     */
    public Footwear createFootwear() {
        return new Footwear();
    }

    /**
     * Create an instance of {@link FruitsVegetables }
     * 
     * @return
     *     the new instance of {@link FruitsVegetables }
     */
    public FruitsVegetables createFruitsVegetables() {
        return new FruitsVegetables();
    }

    /**
     * Create an instance of {@link GeoCoordinates }
     * 
     * @return
     *     the new instance of {@link GeoCoordinates }
     */
    public GeoCoordinates createGeoCoordinates() {
        return new GeoCoordinates();
    }

    /**
     * Create an instance of {@link GeoShape }
     * 
     * @return
     *     the new instance of {@link GeoShape }
     */
    public GeoShape createGeoShape() {
        return new GeoShape();
    }

    /**
     * Create an instance of {@link LocationIDDetails }
     * 
     * @return
     *     the new instance of {@link LocationIDDetails }
     */
    public LocationIDDetails createLocationIDDetails() {
        return new LocationIDDetails();
    }

    /**
     * Create an instance of {@link LocationStatusHistory }
     * 
     * @return
     *     the new instance of {@link LocationStatusHistory }
     */
    public LocationStatusHistory createLocationStatusHistory() {
        return new LocationStatusHistory();
    }

    /**
     * Create an instance of {@link MeatPoultry }
     * 
     * @return
     *     the new instance of {@link MeatPoultry }
     */
    public MeatPoultry createMeatPoultry() {
        return new MeatPoultry();
    }

    /**
     * Create an instance of {@link MilkButterCreamYogurtCheeseEggsSubstitutes }
     * 
     * @return
     *     the new instance of {@link MilkButterCreamYogurtCheeseEggsSubstitutes }
     */
    public MilkButterCreamYogurtCheeseEggsSubstitutes createMilkButterCreamYogurtCheeseEggsSubstitutes() {
        return new MilkButterCreamYogurtCheeseEggsSubstitutes();
    }

    /**
     * Create an instance of {@link NutritionMeasurementType }
     * 
     * @return
     *     the new instance of {@link NutritionMeasurementType }
     */
    public NutritionMeasurementType createNutritionMeasurementType() {
        return new NutritionMeasurementType();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     * @return
     *     the new instance of {@link Offer }
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link OrganicClaimDetails }
     * 
     * @return
     *     the new instance of {@link OrganicClaimDetails }
     */
    public OrganicClaimDetails createOrganicClaimDetails() {
        return new OrganicClaimDetails();
    }

    /**
     * Create an instance of {@link Organization }
     * 
     * @return
     *     the new instance of {@link Organization }
     */
    public Organization createOrganization() {
        return new Organization();
    }

    /**
     * Create an instance of {@link OrganizationIDDetails }
     * 
     * @return
     *     the new instance of {@link OrganizationIDDetails }
     */
    public OrganizationIDDetails createOrganizationIDDetails() {
        return new OrganizationIDDetails();
    }

    /**
     * Create an instance of {@link OrganizationStatusHistory }
     * 
     * @return
     *     the new instance of {@link OrganizationStatusHistory }
     */
    public OrganizationStatusHistory createOrganizationStatusHistory() {
        return new OrganizationStatusHistory();
    }

    /**
     * Create an instance of {@link PackagingDetails }
     * 
     * @return
     *     the new instance of {@link PackagingDetails }
     */
    public PackagingDetails createPackagingDetails() {
        return new PackagingDetails();
    }

    /**
     * Create an instance of {@link PackagingMaterialDetails }
     * 
     * @return
     *     the new instance of {@link PackagingMaterialDetails }
     */
    public PackagingMaterialDetails createPackagingMaterialDetails() {
        return new PackagingMaterialDetails();
    }

    /**
     * Create an instance of {@link Place }
     * 
     * @return
     *     the new instance of {@link Place }
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link PostalAddress }
     * 
     * @return
     *     the new instance of {@link PostalAddress }
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link PriceSpecification }
     * 
     * @return
     *     the new instance of {@link PriceSpecification }
     */
    public PriceSpecification createPriceSpecification() {
        return new PriceSpecification();
    }

    /**
     * Create an instance of {@link Product }
     * 
     * @return
     *     the new instance of {@link Product }
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link ProductYieldDetails }
     * 
     * @return
     *     the new instance of {@link ProductYieldDetails }
     */
    public ProductYieldDetails createProductYieldDetails() {
        return new ProductYieldDetails();
    }

    /**
     * Create an instance of {@link QuantitativeValue }
     * 
     * @return
     *     the new instance of {@link QuantitativeValue }
     */
    public QuantitativeValue createQuantitativeValue() {
        return new QuantitativeValue();
    }

    /**
     * Create an instance of {@link ReferencedFileDetails }
     * 
     * @return
     *     the new instance of {@link ReferencedFileDetails }
     */
    public ReferencedFileDetails createReferencedFileDetails() {
        return new ReferencedFileDetails();
    }

    /**
     * Create an instance of {@link ReturnablePackageDepositDetails }
     * 
     * @return
     *     the new instance of {@link ReturnablePackageDepositDetails }
     */
    public ReturnablePackageDepositDetails createReturnablePackageDepositDetails() {
        return new ReturnablePackageDepositDetails();
    }

    /**
     * Create an instance of {@link Seafood }
     * 
     * @return
     *     the new instance of {@link Seafood }
     */
    public Seafood createSeafood() {
        return new Seafood();
    }

    /**
     * Create an instance of {@link SizeCodeDetails }
     * 
     * @return
     *     the new instance of {@link SizeCodeDetails }
     */
    public SizeCodeDetails createSizeCodeDetails() {
        return new SizeCodeDetails();
    }

    /**
     * Create an instance of {@link SizeDetails }
     * 
     * @return
     *     the new instance of {@link SizeDetails }
     */
    public SizeDetails createSizeDetails() {
        return new SizeDetails();
    }

    /**
     * Create an instance of {@link TargetMarketDetails }
     * 
     * @return
     *     the new instance of {@link TargetMarketDetails }
     */
    public TargetMarketDetails createTargetMarketDetails() {
        return new TargetMarketDetails();
    }

    /**
     * Create an instance of {@link TextileMaterialDetails }
     * 
     * @return
     *     the new instance of {@link TextileMaterialDetails }
     */
    public TextileMaterialDetails createTextileMaterialDetails() {
        return new TextileMaterialDetails();
    }

    /**
     * Create an instance of {@link TypeCode }
     * 
     * @return
     *     the new instance of {@link TypeCode }
     */
    public TypeCode createTypeCode() {
        return new TypeCode();
    }

    /**
     * Create an instance of {@link WarrantyPromise }
     * 
     * @return
     *     the new instance of {@link WarrantyPromise }
     */
    public WarrantyPromise createWarrantyPromise() {
        return new WarrantyPromise();
    }

    /**
     * Create an instance of {@link WearableProduct }
     * 
     * @return
     *     the new instance of {@link WearableProduct }
     */
    public WearableProduct createWearableProduct() {
        return new WearableProduct();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "activityIdeas")
    public JAXBElement<String> createActivityIdeas(String value) {
        return new JAXBElement<>(_ActivityIdeas_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "allergenInfo")
    public JAXBElement<String> createAllergenInfo(String value) {
        return new JAXBElement<>(_AllergenInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "appDownload")
    public JAXBElement<String> createAppDownload(String value) {
        return new JAXBElement<>(_AppDownload_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "brandHomepageClinical")
    public JAXBElement<String> createBrandHomepageClinical(String value) {
        return new JAXBElement<>(_BrandHomepageClinical_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "brandHomepagePatient")
    public JAXBElement<String> createBrandHomepagePatient(String value) {
        return new JAXBElement<>(_BrandHomepagePatient_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "careersInfo")
    public JAXBElement<String> createCareersInfo(String value) {
        return new JAXBElement<>(_CareersInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "certificationInfo")
    public JAXBElement<String> createCertificationInfo(String value) {
        return new JAXBElement<>(_CertificationInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "consumerHandlingStorageInfo")
    public JAXBElement<String> createConsumerHandlingStorageInfo(String value) {
        return new JAXBElement<>(_ConsumerHandlingStorageInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "defaultLink")
    public JAXBElement<String> createDefaultLink(String value) {
        return new JAXBElement<>(_DefaultLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "defaultLinkMulti")
    public JAXBElement<String> createDefaultLinkMulti(String value) {
        return new JAXBElement<>(_DefaultLinkMulti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "epcis")
    public JAXBElement<String> createEpcis(String value) {
        return new JAXBElement<>(_Epcis_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "epil")
    public JAXBElement<String> createEpil(String value) {
        return new JAXBElement<>(_Epil_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "eventsInfo")
    public JAXBElement<String> createEventsInfo(String value) {
        return new JAXBElement<>(_EventsInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "faqs")
    public JAXBElement<String> createFaqs(String value) {
        return new JAXBElement<>(_Faqs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "handledBy")
    public JAXBElement<String> createHandledBy(String value) {
        return new JAXBElement<>(_HandledBy_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "hasRetailers")
    public JAXBElement<String> createHasRetailers(String value) {
        return new JAXBElement<>(_HasRetailers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "homepage")
    public JAXBElement<String> createHomepage(String value) {
        return new JAXBElement<>(_Homepage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ingredientsInfo")
    public JAXBElement<String> createIngredientsInfo(String value) {
        return new JAXBElement<>(_IngredientsInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "instructions")
    public JAXBElement<String> createInstructions(String value) {
        return new JAXBElement<>(_Instructions_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "jws")
    public JAXBElement<String> createJws(String value) {
        return new JAXBElement<>(_Jws_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "leaveReview")
    public JAXBElement<String> createLeaveReview(String value) {
        return new JAXBElement<>(_LeaveReview_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "locationInfo")
    public JAXBElement<String> createLocationInfo(String value) {
        return new JAXBElement<>(_LocationInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "logisticsInfo")
    public JAXBElement<String> createLogisticsInfo(String value) {
        return new JAXBElement<>(_LogisticsInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "loyaltyProgram")
    public JAXBElement<String> createLoyaltyProgram(String value) {
        return new JAXBElement<>(_LoyaltyProgram_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "masterData")
    public JAXBElement<String> createMasterData(String value) {
        return new JAXBElement<>(_MasterData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "menuInfo")
    public JAXBElement<String> createMenuInfo(String value) {
        return new JAXBElement<>(_MenuInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "nutritionalInfo")
    public JAXBElement<String> createNutritionalInfo(String value) {
        return new JAXBElement<>(_NutritionalInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "openingHoursInfo")
    public JAXBElement<String> createOpeningHoursInfo(String value) {
        return new JAXBElement<>(_OpeningHoursInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "paymentLink")
    public JAXBElement<String> createPaymentLink(String value) {
        return new JAXBElement<>(_PaymentLink_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "pip")
    public JAXBElement<String> createPip(String value) {
        return new JAXBElement<>(_Pip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "productSustainabilityInfo")
    public JAXBElement<String> createProductSustainabilityInfo(String value) {
        return new JAXBElement<>(_ProductSustainabilityInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "promotion")
    public JAXBElement<String> createPromotion(String value) {
        return new JAXBElement<>(_Promotion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "purchaseSuppliesOrAccessories")
    public JAXBElement<String> createPurchaseSuppliesOrAccessories(String value) {
        return new JAXBElement<>(_PurchaseSuppliesOrAccessories_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "quickStartGuide")
    public JAXBElement<String> createQuickStartGuide(String value) {
        return new JAXBElement<>(_QuickStartGuide_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "recallStatus")
    public JAXBElement<String> createRecallStatus(String value) {
        return new JAXBElement<>(_RecallStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "recipeInfo")
    public JAXBElement<String> createRecipeInfo(String value) {
        return new JAXBElement<>(_RecipeInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "registerProduct")
    public JAXBElement<String> createRegisterProduct(String value) {
        return new JAXBElement<>(_RegisterProduct_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "registryEntry")
    public JAXBElement<String> createRegistryEntry(String value) {
        return new JAXBElement<>(_RegistryEntry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "relatedImage")
    public JAXBElement<String> createRelatedImage(String value) {
        return new JAXBElement<>(_RelatedImage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "relatedVideo")
    public JAXBElement<String> createRelatedVideo(String value) {
        return new JAXBElement<>(_RelatedVideo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "review")
    public JAXBElement<String> createReview(String value) {
        return new JAXBElement<>(_Review_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "safetyInfo")
    public JAXBElement<String> createSafetyInfo(String value) {
        return new JAXBElement<>(_SafetyInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "scheduleTime")
    public JAXBElement<String> createScheduleTime(String value) {
        return new JAXBElement<>(_ScheduleTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "serviceInfo")
    public JAXBElement<String> createServiceInfo(String value) {
        return new JAXBElement<>(_ServiceInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "smartLabel")
    public JAXBElement<String> createSmartLabel(String value) {
        return new JAXBElement<>(_SmartLabel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "smpc")
    public JAXBElement<String> createSmpc(String value) {
        return new JAXBElement<>(_Smpc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "socialMedia")
    public JAXBElement<String> createSocialMedia(String value) {
        return new JAXBElement<>(_SocialMedia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "statisticInfo")
    public JAXBElement<String> createStatisticInfo(String value) {
        return new JAXBElement<>(_StatisticInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "subscribe")
    public JAXBElement<String> createSubscribe(String value) {
        return new JAXBElement<>(_Subscribe_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "support")
    public JAXBElement<String> createSupport(String value) {
        return new JAXBElement<>(_Support_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "sustainabilityInfo")
    public JAXBElement<String> createSustainabilityInfo(String value) {
        return new JAXBElement<>(_SustainabilityInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "traceability")
    public JAXBElement<String> createTraceability(String value) {
        return new JAXBElement<>(_Traceability_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "tutorial")
    public JAXBElement<String> createTutorial(String value) {
        return new JAXBElement<>(_Tutorial_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "userAgreement")
    public JAXBElement<String> createUserAgreement(String value) {
        return new JAXBElement<>(_UserAgreement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verificationService")
    public JAXBElement<String> createVerificationService(String value) {
        return new JAXBElement<>(_VerificationService_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "whatsInTheBox")
    public JAXBElement<String> createWhatsInTheBox(String value) {
        return new JAXBElement<>(_WhatsInTheBox_QNAME, String.class, null, value);
    }

}
