//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Offer complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Offer">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="acceptedPaymentMethod" type="{}PaymentMethod"/>
 *         <element name="availabilityEnds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="availabilityStarts" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="availableAtOrFrom" type="{}Place"/>
 *         <element name="eligibleQuantity" type="{}QuantitativeValue"/>
 *         <element name="eligibleQuantityMaximum" type="{}QuantitativeValue"/>
 *         <element name="eligibleQuantityMinimum" type="{}QuantitativeValue"/>
 *         <element name="itemOffered" type="{}Product"/>
 *         <element name="offerDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="offerDiscount" type="{}Discount"/>
 *         <element name="offerRedemptionURL" type="{}ReferencedFileDetails"/>
 *         <element name="paymentTerms" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="priceSpecification" type="{}PriceSpecification"/>
 *         <element name="seeker" type="{}Organization"/>
 *         <element name="seller" type="{}Organization"/>
 *         <element name="warranty" type="{}WarrantyPromise"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Offer", propOrder = {
    "acceptedPaymentMethod",
    "availabilityEnds",
    "availabilityStarts",
    "availableAtOrFrom",
    "eligibleQuantity",
    "eligibleQuantityMaximum",
    "eligibleQuantityMinimum",
    "itemOffered",
    "offerDescription",
    "offerDiscount",
    "offerRedemptionURL",
    "paymentTerms",
    "priceSpecification",
    "seeker",
    "seller",
    "warranty"
})
public class Offer {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PaymentMethod acceptedPaymentMethod;
    @XmlElement(required = true)
    protected String availabilityEnds;
    @XmlElement(required = true)
    protected String availabilityStarts;
    @XmlElement(required = true)
    protected Place availableAtOrFrom;
    @XmlElement(required = true)
    protected QuantitativeValue eligibleQuantity;
    @XmlElement(required = true)
    protected QuantitativeValue eligibleQuantityMaximum;
    @XmlElement(required = true)
    protected QuantitativeValue eligibleQuantityMinimum;
    @XmlElement(required = true)
    protected Product itemOffered;
    @XmlElement(required = true)
    protected String offerDescription;
    @XmlElement(required = true)
    protected Discount offerDiscount;
    @XmlElement(required = true)
    protected ReferencedFileDetails offerRedemptionURL;
    @XmlElement(required = true)
    protected String paymentTerms;
    @XmlElement(required = true)
    protected PriceSpecification priceSpecification;
    @XmlElement(required = true)
    protected Organization seeker;
    @XmlElement(required = true)
    protected Organization seller;
    @XmlElement(required = true)
    protected WarrantyPromise warranty;

    /**
     * Gets the value of the acceptedPaymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethod }
     *     
     */
    public PaymentMethod getAcceptedPaymentMethod() {
        return acceptedPaymentMethod;
    }

    /**
     * Sets the value of the acceptedPaymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethod }
     *     
     */
    public void setAcceptedPaymentMethod(PaymentMethod value) {
        this.acceptedPaymentMethod = value;
    }

    /**
     * Gets the value of the availabilityEnds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityEnds() {
        return availabilityEnds;
    }

    /**
     * Sets the value of the availabilityEnds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityEnds(String value) {
        this.availabilityEnds = value;
    }

    /**
     * Gets the value of the availabilityStarts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailabilityStarts() {
        return availabilityStarts;
    }

    /**
     * Sets the value of the availabilityStarts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailabilityStarts(String value) {
        this.availabilityStarts = value;
    }

    /**
     * Gets the value of the availableAtOrFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Place }
     *     
     */
    public Place getAvailableAtOrFrom() {
        return availableAtOrFrom;
    }

    /**
     * Sets the value of the availableAtOrFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place }
     *     
     */
    public void setAvailableAtOrFrom(Place value) {
        this.availableAtOrFrom = value;
    }

    /**
     * Gets the value of the eligibleQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getEligibleQuantity() {
        return eligibleQuantity;
    }

    /**
     * Sets the value of the eligibleQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setEligibleQuantity(QuantitativeValue value) {
        this.eligibleQuantity = value;
    }

    /**
     * Gets the value of the eligibleQuantityMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getEligibleQuantityMaximum() {
        return eligibleQuantityMaximum;
    }

    /**
     * Sets the value of the eligibleQuantityMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setEligibleQuantityMaximum(QuantitativeValue value) {
        this.eligibleQuantityMaximum = value;
    }

    /**
     * Gets the value of the eligibleQuantityMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getEligibleQuantityMinimum() {
        return eligibleQuantityMinimum;
    }

    /**
     * Sets the value of the eligibleQuantityMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setEligibleQuantityMinimum(QuantitativeValue value) {
        this.eligibleQuantityMinimum = value;
    }

    /**
     * Gets the value of the itemOffered property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getItemOffered() {
        return itemOffered;
    }

    /**
     * Sets the value of the itemOffered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setItemOffered(Product value) {
        this.itemOffered = value;
    }

    /**
     * Gets the value of the offerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDescription() {
        return offerDescription;
    }

    /**
     * Sets the value of the offerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDescription(String value) {
        this.offerDescription = value;
    }

    /**
     * Gets the value of the offerDiscount property.
     * 
     * @return
     *     possible object is
     *     {@link Discount }
     *     
     */
    public Discount getOfferDiscount() {
        return offerDiscount;
    }

    /**
     * Sets the value of the offerDiscount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Discount }
     *     
     */
    public void setOfferDiscount(Discount value) {
        this.offerDiscount = value;
    }

    /**
     * Gets the value of the offerRedemptionURL property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public ReferencedFileDetails getOfferRedemptionURL() {
        return offerRedemptionURL;
    }

    /**
     * Sets the value of the offerRedemptionURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public void setOfferRedemptionURL(ReferencedFileDetails value) {
        this.offerRedemptionURL = value;
    }

    /**
     * Gets the value of the paymentTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentTerms() {
        return paymentTerms;
    }

    /**
     * Sets the value of the paymentTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentTerms(String value) {
        this.paymentTerms = value;
    }

    /**
     * Gets the value of the priceSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link PriceSpecification }
     *     
     */
    public PriceSpecification getPriceSpecification() {
        return priceSpecification;
    }

    /**
     * Sets the value of the priceSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceSpecification }
     *     
     */
    public void setPriceSpecification(PriceSpecification value) {
        this.priceSpecification = value;
    }

    /**
     * Gets the value of the seeker property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getSeeker() {
        return seeker;
    }

    /**
     * Sets the value of the seeker property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setSeeker(Organization value) {
        this.seeker = value;
    }

    /**
     * Gets the value of the seller property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getSeller() {
        return seller;
    }

    /**
     * Sets the value of the seller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setSeller(Organization value) {
        this.seller = value;
    }

    /**
     * Gets the value of the warranty property.
     * 
     * @return
     *     possible object is
     *     {@link WarrantyPromise }
     *     
     */
    public WarrantyPromise getWarranty() {
        return warranty;
    }

    /**
     * Sets the value of the warranty property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarrantyPromise }
     *     
     */
    public void setWarranty(WarrantyPromise value) {
        this.warranty = value;
    }

}
