//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for OrganizationRoleType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="OrganizationRoleType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="ACCEPTING_PARTY"/>
 *     <enumeration value="BILL_OF_LADING_RECIPIENT"/>
 *     <enumeration value="BILL_TO"/>
 *     <enumeration value="BRAND_OWNER"/>
 *     <enumeration value="BREEDER"/>
 *     <enumeration value="BROKER_AGENT"/>
 *     <enumeration value="BUYER"/>
 *     <enumeration value="BUYERS_AGENT_REPRESENTATIVE"/>
 *     <enumeration value="CARRIER"/>
 *     <enumeration value="CENTRAL_PAYMENT_SERVICE"/>
 *     <enumeration value="CHECKING_PARTY"/>
 *     <enumeration value="CHEQUE_ORDER"/>
 *     <enumeration value="CONSIGNEE"/>
 *     <enumeration value="CONSOLIDATOR"/>
 *     <enumeration value="CONSUMER"/>
 *     <enumeration value="CORPORATE_IDENTITY"/>
 *     <enumeration value="CUSTOMS"/>
 *     <enumeration value="CUSTOMS_BROKER"/>
 *     <enumeration value="CUTTER"/>
 *     <enumeration value="DECLARANTS_AGENT_REPRESENTATIVE"/>
 *     <enumeration value="DELIVERY_PARTY"/>
 *     <enumeration value="DESIGNER"/>
 *     <enumeration value="DESPATCH_PARTY"/>
 *     <enumeration value="DISTRIBUTOR"/>
 *     <enumeration value="DOCK_DOOR"/>
 *     <enumeration value="EMPTY_EQUIPMENT_DESPATCH_PARTY"/>
 *     <enumeration value="EMPTY_EQUIPMENT_RETURN_PARTY"/>
 *     <enumeration value="EQUIPMENT_OWNER"/>
 *     <enumeration value="EXPORTER"/>
 *     <enumeration value="FACTOR"/>
 *     <enumeration value="FATTENER"/>
 *     <enumeration value="FREIGHT_FORWARDER"/>
 *     <enumeration value="GOODS_OWNER"/>
 *     <enumeration value="GROWER"/>
 *     <enumeration value="HEAD_OFFICE"/>
 *     <enumeration value="IMPORTER"/>
 *     <enumeration value="INFORMATION_PROVIDER"/>
 *     <enumeration value="INSURER"/>
 *     <enumeration value="INTERMEDIARY_BANK_1"/>
 *     <enumeration value="INTERMEDIARY_BANK_2"/>
 *     <enumeration value="INVENTORY_CONTROLLER"/>
 *     <enumeration value="INVENTORY_REPORTING_PARTY"/>
 *     <enumeration value="INVOICEE"/>
 *     <enumeration value="ISSUER_OF_INVOICE"/>
 *     <enumeration value="LOGISTICS_SERVICE_PROVIDER"/>
 *     <enumeration value="MANUFACTURER_OF_GOODS"/>
 *     <enumeration value="MANUFACTURING_PLANT"/>
 *     <enumeration value="MARK_FOR"/>
 *     <enumeration value="MESSAGE_FROM"/>
 *     <enumeration value="MESSAGE_RECIPIENT"/>
 *     <enumeration value="MINCER"/>
 *     <enumeration value="OPERATING_DIVISION"/>
 *     <enumeration value="OPERATOR"/>
 *     <enumeration value="ORDERING_PARTY"/>
 *     <enumeration value="OWNER_OF_EQUIPMENT"/>
 *     <enumeration value="OWNER_OF_MEANS_OF_TRANSPORT"/>
 *     <enumeration value="PARTY_DECLARING_THE_VALUE_ADDED_TAX"/>
 *     <enumeration value="PARTY_FOR_WHOM_ITEM_IS_ULTIMATELY_INTENDED"/>
 *     <enumeration value="PARTY_RECEIVING_PRIVATE_DATA"/>
 *     <enumeration value="PARTY_RECOVERING_THE_VALUE_ADDED_TAX"/>
 *     <enumeration value="PARTY_TO_RECEIVE_ALL_DOCUMENTS"/>
 *     <enumeration value="PARTY_TO_RECEIVE_COMMERCIAL_INVOICE"/>
 *     <enumeration value="PARTY_TO_RECEIVE_ELECTRONIC_MEMO_OF_INVOICE"/>
 *     <enumeration value="PARTY_TO_RECEIVE_FREIGHT_BILL"/>
 *     <enumeration value="PARTY_TO_RECEIVE_REFUND"/>
 *     <enumeration value="PAYEE"/>
 *     <enumeration value="PAYER"/>
 *     <enumeration value="POINT_OF_SALE"/>
 *     <enumeration value="PRICE_LOCATION_PARTY"/>
 *     <enumeration value="PROXY"/>
 *     <enumeration value="PUBLIC_WAREHOUSE"/>
 *     <enumeration value="PURCHASE_ORDER_RECEIVER"/>
 *     <enumeration value="REGISTERED_AGENT"/>
 *     <enumeration value="REMIT_TO"/>
 *     <enumeration value="RETURNABLE_ASSET_SERVICE_CENTRE"/>
 *     <enumeration value="SELLER"/>
 *     <enumeration value="SERVICE_PROVIDER"/>
 *     <enumeration value="SHIP_FROM"/>
 *     <enumeration value="SHIP_TO"/>
 *     <enumeration value="SLAUGHTERER"/>
 *     <enumeration value="STORE"/>
 *     <enumeration value="SUBSTITUTE_SUPPLIER"/>
 *     <enumeration value="SUPPLIER"/>
 *     <enumeration value="TRANSPORTATION_CARRIER"/>
 *     <enumeration value="VISITING_ADDRESS"/>
 *     <enumeration value="WAREHOUSE_AND_OR_DEPOT"/>
 *     <enumeration value="WAREHOUSE_KEEPER"/>
 *     <enumeration value="WHOLESALER"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "OrganizationRoleType")
@XmlEnum
public enum OrganizationRoleType {

    ACCEPTING_PARTY,
    BILL_OF_LADING_RECIPIENT,
    BILL_TO,
    BRAND_OWNER,
    BREEDER,
    BROKER_AGENT,
    BUYER,
    BUYERS_AGENT_REPRESENTATIVE,
    CARRIER,
    CENTRAL_PAYMENT_SERVICE,
    CHECKING_PARTY,
    CHEQUE_ORDER,
    CONSIGNEE,
    CONSOLIDATOR,
    CONSUMER,
    CORPORATE_IDENTITY,
    CUSTOMS,
    CUSTOMS_BROKER,
    CUTTER,
    DECLARANTS_AGENT_REPRESENTATIVE,
    DELIVERY_PARTY,
    DESIGNER,
    DESPATCH_PARTY,
    DISTRIBUTOR,
    DOCK_DOOR,
    EMPTY_EQUIPMENT_DESPATCH_PARTY,
    EMPTY_EQUIPMENT_RETURN_PARTY,
    EQUIPMENT_OWNER,
    EXPORTER,
    FACTOR,
    FATTENER,
    FREIGHT_FORWARDER,
    GOODS_OWNER,
    GROWER,
    HEAD_OFFICE,
    IMPORTER,
    INFORMATION_PROVIDER,
    INSURER,
    INTERMEDIARY_BANK_1,
    INTERMEDIARY_BANK_2,
    INVENTORY_CONTROLLER,
    INVENTORY_REPORTING_PARTY,
    INVOICEE,
    ISSUER_OF_INVOICE,
    LOGISTICS_SERVICE_PROVIDER,
    MANUFACTURER_OF_GOODS,
    MANUFACTURING_PLANT,
    MARK_FOR,
    MESSAGE_FROM,
    MESSAGE_RECIPIENT,
    MINCER,
    OPERATING_DIVISION,
    OPERATOR,
    ORDERING_PARTY,
    OWNER_OF_EQUIPMENT,
    OWNER_OF_MEANS_OF_TRANSPORT,
    PARTY_DECLARING_THE_VALUE_ADDED_TAX,
    PARTY_FOR_WHOM_ITEM_IS_ULTIMATELY_INTENDED,
    PARTY_RECEIVING_PRIVATE_DATA,
    PARTY_RECOVERING_THE_VALUE_ADDED_TAX,
    PARTY_TO_RECEIVE_ALL_DOCUMENTS,
    PARTY_TO_RECEIVE_COMMERCIAL_INVOICE,
    PARTY_TO_RECEIVE_ELECTRONIC_MEMO_OF_INVOICE,
    PARTY_TO_RECEIVE_FREIGHT_BILL,
    PARTY_TO_RECEIVE_REFUND,
    PAYEE,
    PAYER,
    POINT_OF_SALE,
    PRICE_LOCATION_PARTY,
    PROXY,
    PUBLIC_WAREHOUSE,
    PURCHASE_ORDER_RECEIVER,
    REGISTERED_AGENT,
    REMIT_TO,
    RETURNABLE_ASSET_SERVICE_CENTRE,
    SELLER,
    SERVICE_PROVIDER,
    SHIP_FROM,
    SHIP_TO,
    SLAUGHTERER,
    STORE,
    SUBSTITUTE_SUPPLIER,
    SUPPLIER,
    TRANSPORTATION_CARRIER,
    VISITING_ADDRESS,
    WAREHOUSE_AND_OR_DEPOT,
    WAREHOUSE_KEEPER,
    WHOLESALER;

    public String value() {
        return name();
    }

    public static OrganizationRoleType fromValue(String v) {
        return valueOf(v);
    }

}
