/*
 * Copyright 2022-2026 benelog GmbH & Co. KG
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for PackagingFeatureCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="PackagingFeatureCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BASE"/>
 *     <enumeration value="BEAM"/>
 *     <enumeration value="BUNG_SEAL"/>
 *     <enumeration value="CAP"/>
 *     <enumeration value="CARRIER"/>
 *     <enumeration value="CONSUMPTION_UTENSIL"/>
 *     <enumeration value="CORE"/>
 *     <enumeration value="CREEL"/>
 *     <enumeration value="EDGE_PROTECTION"/>
 *     <enumeration value="HANDLE"/>
 *     <enumeration value="INNER_CONTAINER"/>
 *     <enumeration value="INTERNAL_DIVIDER"/>
 *     <enumeration value="LABEL"/>
 *     <enumeration value="LID"/>
 *     <enumeration value="LINER"/>
 *     <enumeration value="LUG"/>
 *     <enumeration value="NESTING_EDGE"/>
 *     <enumeration value="PEG"/>
 *     <enumeration value="PULL_OFF_TAB"/>
 *     <enumeration value="RING_HOLDER"/>
 *     <enumeration value="RIVET"/>
 *     <enumeration value="SLEEVE"/>
 *     <enumeration value="SPOUT"/>
 *     <enumeration value="TAG"/>
 *     <enumeration value="WICKER_OUTER_CONTAINER"/>
 *     <enumeration value="WRAP"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "PackagingFeatureCode")
@XmlEnum
public enum PackagingFeatureCode {
  BASE,
  BEAM,
  BUNG_SEAL,
  CAP,
  CARRIER,
  CONSUMPTION_UTENSIL,
  CORE,
  CREEL,
  EDGE_PROTECTION,
  HANDLE,
  INNER_CONTAINER,
  INTERNAL_DIVIDER,
  LABEL,
  LID,
  LINER,
  LUG,
  NESTING_EDGE,
  PEG,
  PULL_OFF_TAB,
  RING_HOLDER,
  RIVET,
  SLEEVE,
  SPOUT,
  TAG,
  WICKER_OUTER_CONTAINER,
  WRAP;

  public String value() {
    return name();
  }

  public static PackagingFeatureCode fromValue(String v) {
    return valueOf(v);
  }
}
