//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for PackagingMarkedLabelAccreditationCode</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="PackagingMarkedLabelAccreditationCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="AMA_ORGANIC_SEAL"/>
 *     <enumeration value="AUS_KAUP_ESTONIA"/>
 *     <enumeration value="BDIH_LOGO"/>
 *     <enumeration value="BETER_LEVEN_1_STER"/>
 *     <enumeration value="BETER_LEVEN_2_STER"/>
 *     <enumeration value="BETER_LEVEN_3_STER"/>
 *     <enumeration value="BIO_AUSTRIA_LABEL"/>
 *     <enumeration value="BIO_LABEL_GERMAN"/>
 *     <enumeration value="BIO_SUISSE_BUD_SEAL"/>
 *     <enumeration value="BLUE_ANGEL"/>
 *     <enumeration value="BORD_BIA_APPROVED"/>
 *     <enumeration value="BORD_BIA_APPROVED_MEAT"/>
 *     <enumeration value="BRA_MILJOVAL_LABEL_SWEDISH"/>
 *     <enumeration value="CROSSED_GRAIN_SYMBOL"/>
 *     <enumeration value="DEMETER_LABEL"/>
 *     <enumeration value="ECOCERT_CERTIFICATE"/>
 *     <enumeration value="ECO_LABEL_LADYBUG"/>
 *     <enumeration value="EC_NATIONAL_HEALTH_MARK"/>
 *     <enumeration value="EESTI_OKOMARK"/>
 *     <enumeration value="EESTI_PARIM_TOIDUAINE"/>
 *     <enumeration value="EKO"/>
 *     <enumeration value="EU_ECO_LABEL"/>
 *     <enumeration value="EU_ORGANIC_FARMING"/>
 *     <enumeration value="FAIR_TRADE_MARK"/>
 *     <enumeration value="FALKEN"/>
 *     <enumeration value="FINNISH_HEART_SYMBOL"/>
 *     <enumeration value="FOREST_STEWARDSHIP_COUNCIL_LABEL"/>
 *     <enumeration value="GMO_MARKED"/>
 *     <enumeration value="GOODS_FROM_FINLAND_BLUE_SWAN"/>
 *     <enumeration value="GREEN_DOT"/>
 *     <enumeration value="GREEN_RESTAURANT_ASSOCIATION_ENDORSED"/>
 *     <enumeration value="GREEN_SEAL_CERTIFIED"/>
 *     <enumeration value="GUARANTEED_IRISH"/>
 *     <enumeration value="KRAV_MARK"/>
 *     <enumeration value="LABEL_OF_THE_ALLERGY_AND_ASTHMA_FEDERATION"/>
 *     <enumeration value="LEAPING_BUNNY"/>
 *     <enumeration value="LOODUSSOBRALIK_TOODE_ESTONIA"/>
 *     <enumeration value="LOVE_IRISH_FOOD"/>
 *     <enumeration value="MADE_IN_FINLAND_FLAG_WITH_KEY"/>
 *     <enumeration value="MARINE_STEWARDSHIP_COUNCIL_LABEL"/>
 *     <enumeration value="MAX_HAVELAAR"/>
 *     <enumeration value="NATRUE_LABEL"/>
 *     <enumeration value="NYCKELHALET"/>
 *     <enumeration value="OEKO_TEX_LABEL"/>
 *     <enumeration value="OFFICIAL_ECO_LABEL_SUN"/>
 *     <enumeration value="PEFC"/>
 *     <enumeration value="PROTECTED_DESIGNATION_OF_ORIGIN"/>
 *     <enumeration value="PROTECTED_GEOGRAPHICAL_INDICATION"/>
 *     <enumeration value="PROTECTED_HARVEST_CERTIFIED"/>
 *     <enumeration value="QUALITY_MARK_IRELAND"/>
 *     <enumeration value="RAINFOREST_ALLIANCE"/>
 *     <enumeration value="SCHARRELVLEES"/>
 *     <enumeration value="SOIL_ASSOCIATION_ORGANIC_SYMBOL"/>
 *     <enumeration value="SUSTAINABLE_PALM_OIL_RSPO"/>
 *     <enumeration value="SVANEN"/>
 *     <enumeration value="SWEDISH_SEAL_OF_QUALITY"/>
 *     <enumeration value="TRADITIONAL_SPECIALTY_GUARANTEED"/>
 *     <enumeration value="TUNNUSTATUD_EESTI_MAITSE"/>
 *     <enumeration value="TUNNUSTATUD_MAITSE"/>
 *     <enumeration value="UNIQUELY_FINNISH"/>
 *     <enumeration value="USDA"/>
 *     <enumeration value="UTZ_CERTIFIED"/>
 *     <enumeration value="VAELG_FULDKORN_FORST"/>
 *     <enumeration value="WWF_PANDA_LABEL"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "PackagingMarkedLabelAccreditationCode")
@XmlEnum
public enum PackagingMarkedLabelAccreditationCode {

    AMA_ORGANIC_SEAL,
    AUS_KAUP_ESTONIA,
    BDIH_LOGO,
    BETER_LEVEN_1_STER,
    BETER_LEVEN_2_STER,
    BETER_LEVEN_3_STER,
    BIO_AUSTRIA_LABEL,
    BIO_LABEL_GERMAN,
    BIO_SUISSE_BUD_SEAL,
    BLUE_ANGEL,
    BORD_BIA_APPROVED,
    BORD_BIA_APPROVED_MEAT,
    BRA_MILJOVAL_LABEL_SWEDISH,
    CROSSED_GRAIN_SYMBOL,
    DEMETER_LABEL,
    ECOCERT_CERTIFICATE,
    ECO_LABEL_LADYBUG,
    EC_NATIONAL_HEALTH_MARK,
    EESTI_OKOMARK,
    EESTI_PARIM_TOIDUAINE,
    EKO,
    EU_ECO_LABEL,
    EU_ORGANIC_FARMING,
    FAIR_TRADE_MARK,
    FALKEN,
    FINNISH_HEART_SYMBOL,
    FOREST_STEWARDSHIP_COUNCIL_LABEL,
    GMO_MARKED,
    GOODS_FROM_FINLAND_BLUE_SWAN,
    GREEN_DOT,
    GREEN_RESTAURANT_ASSOCIATION_ENDORSED,
    GREEN_SEAL_CERTIFIED,
    GUARANTEED_IRISH,
    KRAV_MARK,
    LABEL_OF_THE_ALLERGY_AND_ASTHMA_FEDERATION,
    LEAPING_BUNNY,
    LOODUSSOBRALIK_TOODE_ESTONIA,
    LOVE_IRISH_FOOD,
    MADE_IN_FINLAND_FLAG_WITH_KEY,
    MARINE_STEWARDSHIP_COUNCIL_LABEL,
    MAX_HAVELAAR,
    NATRUE_LABEL,
    NYCKELHALET,
    OEKO_TEX_LABEL,
    OFFICIAL_ECO_LABEL_SUN,
    PEFC,
    PROTECTED_DESIGNATION_OF_ORIGIN,
    PROTECTED_GEOGRAPHICAL_INDICATION,
    PROTECTED_HARVEST_CERTIFIED,
    QUALITY_MARK_IRELAND,
    RAINFOREST_ALLIANCE,
    SCHARRELVLEES,
    SOIL_ASSOCIATION_ORGANIC_SYMBOL,
    SUSTAINABLE_PALM_OIL_RSPO,
    SVANEN,
    SWEDISH_SEAL_OF_QUALITY,
    TRADITIONAL_SPECIALTY_GUARANTEED,
    TUNNUSTATUD_EESTI_MAITSE,
    TUNNUSTATUD_MAITSE,
    UNIQUELY_FINNISH,
    USDA,
    UTZ_CERTIFIED,
    VAELG_FULDKORN_FORST,
    WWF_PANDA_LABEL;

    public String value() {
        return name();
    }

    public static PackagingMarkedLabelAccreditationCode fromValue(String v) {
        return valueOf(v);
    }

}
