//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for PackagingMaterialTypeCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="PackagingMaterialTypeCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BAMBOO"/>
 *     <enumeration value="CELLULOSE_HYDRATE"/>
 *     <enumeration value="CERAMIC"/>
 *     <enumeration value="CLOTH_OR_FABRIC"/>
 *     <enumeration value="COMPOSITE"/>
 *     <enumeration value="CORK_NATURAL"/>
 *     <enumeration value="CORRUGATED_BOARD_DOUBLE_WALL"/>
 *     <enumeration value="CORRUGATED_BOARD_OTHER"/>
 *     <enumeration value="CORRUGATED_BOARD_SINGLE_WALL"/>
 *     <enumeration value="CORRUGATED_BOARD_TRIPLE_WALL"/>
 *     <enumeration value="FIBRE_BURLAP"/>
 *     <enumeration value="FIBRE_COTTON"/>
 *     <enumeration value="FIBRE_FLAX"/>
 *     <enumeration value="FIBRE_HEMP"/>
 *     <enumeration value="FIBRE_JUTE"/>
 *     <enumeration value="FIBRE_OTHER"/>
 *     <enumeration value="FOAM"/>
 *     <enumeration value="GLASS"/>
 *     <enumeration value="GLASS_BOROSILICATE"/>
 *     <enumeration value="GLASS_COLOURED"/>
 *     <enumeration value="GLASS_CRYSTAL"/>
 *     <enumeration value="LAMINATED_CARTON"/>
 *     <enumeration value="METAL_ALUMINUM"/>
 *     <enumeration value="METAL_BRASS"/>
 *     <enumeration value="METAL_COMPOSITE"/>
 *     <enumeration value="METAL_IRON"/>
 *     <enumeration value="METAL_LEAD"/>
 *     <enumeration value="METAL_OTHER"/>
 *     <enumeration value="METAL_STAINLESS_STEEL"/>
 *     <enumeration value="METAL_STEEL"/>
 *     <enumeration value="METAL_TIN"/>
 *     <enumeration value="METAL_ZAMAC"/>
 *     <enumeration value="MINERAL_CALCIUM_CARBONATE"/>
 *     <enumeration value="MINERAL_OTHER"/>
 *     <enumeration value="MINERAL_TALC"/>
 *     <enumeration value="NATURAL_RUBBER"/>
 *     <enumeration value="OTHER"/>
 *     <enumeration value="PAPER_CORRUGATED"/>
 *     <enumeration value="PAPER_KRAFT"/>
 *     <enumeration value="PAPER_KRAFT_WET_STRENGTH"/>
 *     <enumeration value="PAPER_MOLDED_PULP"/>
 *     <enumeration value="PAPER_OTHER"/>
 *     <enumeration value="PAPER_PAPER"/>
 *     <enumeration value="PAPER_PAPERBOARD"/>
 *     <enumeration value="PAPER_RAYON"/>
 *     <enumeration value="PLANT_LEAVES"/>
 *     <enumeration value="PLASTIC_BIOPLASTIC"/>
 *     <enumeration value="PLASTIC_OTHER"/>
 *     <enumeration value="PLASTIC_THERMOPLASTICS"/>
 *     <enumeration value="POLYMER_APET"/>
 *     <enumeration value="POLYMER_BOPP"/>
 *     <enumeration value="POLYMER_CELLULOSE_ACETATE"/>
 *     <enumeration value="POLYMER_CPET"/>
 *     <enumeration value="POLYMER_EPE"/>
 *     <enumeration value="POLYMER_EPOXY"/>
 *     <enumeration value="POLYMER_EPS"/>
 *     <enumeration value="POLYMER_EVA"/>
 *     <enumeration value="POLYMER_EVOH"/>
 *     <enumeration value="POLYMER_HDPE"/>
 *     <enumeration value="POLYMER_IONOMER"/>
 *     <enumeration value="POLYMER_LDPE"/>
 *     <enumeration value="POLYMER_LLDPE"/>
 *     <enumeration value="POLYMER_MDPE"/>
 *     <enumeration value="POLYMER_MIX"/>
 *     <enumeration value="POLYMER_NYLON"/>
 *     <enumeration value="POLYMER_OPP"/>
 *     <enumeration value="POLYMER_OTHER"/>
 *     <enumeration value="POLYMER_PA"/>
 *     <enumeration value="POLYMER_PAN"/>
 *     <enumeration value="POLYMER_PC"/>
 *     <enumeration value="POLYMER_PCL"/>
 *     <enumeration value="POLYMER_PE"/>
 *     <enumeration value="POLYMER_PEN"/>
 *     <enumeration value="POLYMER_PET"/>
 *     <enumeration value="POLYMER_PETG"/>
 *     <enumeration value="POLYMER_PHA"/>
 *     <enumeration value="POLYMER_PLA"/>
 *     <enumeration value="POLYMER_PMMA"/>
 *     <enumeration value="POLYMER_POM"/>
 *     <enumeration value="POLYMER_PP"/>
 *     <enumeration value="POLYMER_PS"/>
 *     <enumeration value="POLYMER_PU"/>
 *     <enumeration value="POLYMER_PVA"/>
 *     <enumeration value="POLYMER_PVC"/>
 *     <enumeration value="POLYMER_PVDC"/>
 *     <enumeration value="POLYMER_SAN"/>
 *     <enumeration value="POLYMER_SILICONE"/>
 *     <enumeration value="POLYMER_TPS"/>
 *     <enumeration value="POLYMER_XPS"/>
 *     <enumeration value="RUBBER"/>
 *     <enumeration value="VINYL"/>
 *     <enumeration value="WOOD_HARDBOARD"/>
 *     <enumeration value="WOOD_HARDWOOD"/>
 *     <enumeration value="WOOD_MEDIUM_DENSITY_FIBREBOARD"/>
 *     <enumeration value="WOOD_ORIENTED_STRANDBOARD"/>
 *     <enumeration value="WOOD_OTHER"/>
 *     <enumeration value="WOOD_PARTICLE_BOARD"/>
 *     <enumeration value="WOOD_PLYWOOD"/>
 *     <enumeration value="WOOD_SOFTWOOD"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "PackagingMaterialTypeCode")
@XmlEnum
public enum PackagingMaterialTypeCode {
  BAMBOO,
  CELLULOSE_HYDRATE,
  CERAMIC,
  CLOTH_OR_FABRIC,
  COMPOSITE,
  CORK_NATURAL,
  CORRUGATED_BOARD_DOUBLE_WALL,
  CORRUGATED_BOARD_OTHER,
  CORRUGATED_BOARD_SINGLE_WALL,
  CORRUGATED_BOARD_TRIPLE_WALL,
  FIBRE_BURLAP,
  FIBRE_COTTON,
  FIBRE_FLAX,
  FIBRE_HEMP,
  FIBRE_JUTE,
  FIBRE_OTHER,
  FOAM,
  GLASS,
  GLASS_BOROSILICATE,
  GLASS_COLOURED,
  GLASS_CRYSTAL,
  LAMINATED_CARTON,
  METAL_ALUMINUM,
  METAL_BRASS,
  METAL_COMPOSITE,
  METAL_IRON,
  METAL_LEAD,
  METAL_OTHER,
  METAL_STAINLESS_STEEL,
  METAL_STEEL,
  METAL_TIN,
  METAL_ZAMAC,
  MINERAL_CALCIUM_CARBONATE,
  MINERAL_OTHER,
  MINERAL_TALC,
  NATURAL_RUBBER,
  OTHER,
  PAPER_CORRUGATED,
  PAPER_KRAFT,
  PAPER_KRAFT_WET_STRENGTH,
  PAPER_MOLDED_PULP,
  PAPER_OTHER,
  PAPER_PAPER,
  PAPER_PAPERBOARD,
  PAPER_RAYON,
  PLANT_LEAVES,
  PLASTIC_BIOPLASTIC,
  PLASTIC_OTHER,
  PLASTIC_THERMOPLASTICS,
  POLYMER_APET,
  POLYMER_BOPP,
  POLYMER_CELLULOSE_ACETATE,
  POLYMER_CPET,
  POLYMER_EPE,
  POLYMER_EPOXY,
  POLYMER_EPS,
  POLYMER_EVA,
  POLYMER_EVOH,
  POLYMER_HDPE,
  POLYMER_IONOMER,
  POLYMER_LDPE,
  POLYMER_LLDPE,
  POLYMER_MDPE,
  POLYMER_MIX,
  POLYMER_NYLON,
  POLYMER_OPP,
  POLYMER_OTHER,
  POLYMER_PA,
  POLYMER_PAN,
  POLYMER_PC,
  POLYMER_PCL,
  POLYMER_PE,
  POLYMER_PEN,
  POLYMER_PET,
  POLYMER_PETG,
  POLYMER_PHA,
  POLYMER_PLA,
  POLYMER_PMMA,
  POLYMER_POM,
  POLYMER_PP,
  POLYMER_PS,
  POLYMER_PU,
  POLYMER_PVA,
  POLYMER_PVC,
  POLYMER_PVDC,
  POLYMER_SAN,
  POLYMER_SILICONE,
  POLYMER_TPS,
  POLYMER_XPS,
  RUBBER,
  VINYL,
  WOOD_HARDBOARD,
  WOOD_HARDWOOD,
  WOOD_MEDIUM_DENSITY_FIBREBOARD,
  WOOD_ORIENTED_STRANDBOARD,
  WOOD_OTHER,
  WOOD_PARTICLE_BOARD,
  WOOD_PLYWOOD,
  WOOD_SOFTWOOD;

  public String value() {
    return name();
  }

  public static PackagingMaterialTypeCode fromValue(String v) {
    return valueOf(v);
  }
}
