//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.ContactPoint;
import io.openepcis.model.interfaces.LocationIDDetails;
import io.openepcis.model.interfaces.LocationStatusHistory;
import io.openepcis.model.interfaces.Place;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Place complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Place">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="additionalLocationID" type="{}LocationID_Details"/>
 *         <element name="address" type="{}PostalAddress"/>
 *         <element name="afterHoursContact" type="{}ContactPoint"/>
 *         <element name="baseLocation" type="{}Place"/>
 *         <element name="certification" type="{}CertificationDetails"/>
 *         <element name="contactPoint" type="{}ContactPoint"/>
 *         <element name="containedInPlace" type="{}Place"/>
 *         <element name="containsPlace" type="{}Place"/>
 *         <element name="digitalAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="digitalLocationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="geo" type="{}Place"/>
 *         <element name="glnType" type="{}GLN_TypeCode"/>
 *         <element name="globalLocationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="leasedFrom" type="{}Organization"/>
 *         <element name="leasedTo" type="{}Organization"/>
 *         <element name="locationGLN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="locationHistory" type="{}LocationStatusHistory"/>
 *         <element name="locationRole" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="managedBy" type="{}Organization"/>
 *         <element name="managedFor" type="{}Organization"/>
 *         <element name="occupiedBy" type="{}Organization"/>
 *         <element name="ownedBy" type="{}Organization"/>
 *         <element name="physicalLocationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="primaryLocationOf" type="{}Organization"/>
 *         <element name="relatedOrganization" type="{}Organization"/>
 *         <element name="replacedByPlace" type="{}Place"/>
 *         <element name="replacedPlace" type="{}Place"/>
 *         <element name="responsibleOrganization" type="{}Organization"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Place", propOrder = {
    "additionalLocationID",
    "address",
    "afterHoursContact",
    "baseLocation",
    "certification",
    "contactPoint",
    "containedInPlace",
    "containsPlace",
    "digitalAddress",
    "digitalLocationName",
    "geo",
    "glnType",
    "globalLocationNumber",
    "leasedFrom",
    "leasedTo",
    "locationGLN",
    "locationHistory",
    "locationRole",
    "managedBy",
    "managedFor",
    "occupiedBy",
    "ownedBy",
    "physicalLocationName",
    "primaryLocationOf",
    "relatedOrganization",
    "replacedByPlace",
    "replacedPlace",
    "responsibleOrganization"
})
public class PlaceXMLImpl implements Place {

    @XmlElement(required = true)
    protected LocationIDDetails additionalLocationID;
    @XmlElement(required = true)
    protected PostalAddressXMLImpl address;
    @XmlElement(required = true)
    protected ContactPoint afterHoursContact;
    @XmlElement(required = true)
    protected PlaceXMLImpl baseLocation;
    @XmlElement(required = true)
    protected CertificationDetailsXMLImpl certification;
    @XmlElement(required = true)
    protected ContactPoint contactPoint;
    @XmlElement(required = true)
    protected PlaceXMLImpl containedInPlaceXMLImpl;
    @XmlElement(required = true)
    protected PlaceXMLImpl containsPlaceXMLImpl;
    @XmlElement(required = true)
    protected String digitalAddress;
    @XmlElement(required = true)
    protected String digitalLocationName;
    @XmlElement(required = true)
    protected PlaceXMLImpl geo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected GLNTypeCode glnType;
    @XmlElement(required = true)
    protected String globalLocationNumber;
    @XmlElement(required = true)
    protected OrganizationXMLImpl leasedFrom;
    @XmlElement(required = true)
    protected OrganizationXMLImpl leasedTo;
    @XmlElement(required = true)
    protected String locationGLN;
    @XmlElement(required = true)
    protected LocationStatusHistory locationHistory;
    @XmlElement(required = true)
    protected String locationRole;
    @XmlElement(required = true)
    protected OrganizationXMLImpl managedBy;
    @XmlElement(required = true)
    protected OrganizationXMLImpl managedFor;
    @XmlElement(required = true)
    protected OrganizationXMLImpl occupiedBy;
    @XmlElement(required = true)
    protected OrganizationXMLImpl ownedBy;
    @XmlElement(required = true)
    protected String physicalLocationName;
    @XmlElement(required = true)
    protected OrganizationXMLImpl primaryLocationOf;
    @XmlElement(required = true)
    protected OrganizationXMLImpl relatedOrganizationXMLImpl;
    @XmlElement(required = true)
    protected PlaceXMLImpl replacedByPlaceXMLImpl;
    @XmlElement(required = true)
    protected PlaceXMLImpl replacedPlaceXMLImpl;
    @XmlElement(required = true)
    protected OrganizationXMLImpl responsibleOrganizationXMLImpl;

    /**
     * Gets the value of the additionalLocationID property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIDDetailsXMLImpl }
     *     
     */
    @Override
    public LocationIDDetails getAdditionalLocationID() {
        return additionalLocationID;
    }

    /**
     * Sets the value of the additionalLocationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIDDetailsXMLImpl }
     *     
     */
    @Override
    public void setAdditionalLocationID(LocationIDDetails value) {
        this.additionalLocationID = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link PostalAddressXMLImpl }
     *     
     */
    @Override
    public PostalAddressXMLImpl getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostalAddressXMLImpl }
     *     
     */
    @Override
    public void setAddress(PostalAddressXMLImpl value) {
        this.address = value;
    }

    /**
     * Gets the value of the afterHoursContact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPointXMLImpl }
     *     
     */
    @Override
    public ContactPoint getAfterHoursContact() {
        return afterHoursContact;
    }

    /**
     * Sets the value of the afterHoursContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPointXMLImpl }
     *     
     */
    @Override
    public void setAfterHoursContact(ContactPoint value) {
        this.afterHoursContact = value;
    }

    /**
     * Gets the value of the baseLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public PlaceXMLImpl getBaseLocation() {
        return baseLocation;
    }

    /**
     * Sets the value of the baseLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public void setBaseLocation(PlaceXMLImpl value) {
        this.baseLocation = value;
    }

    /**
     * Gets the value of the certification property.
     * 
     * @return
     *     possible object is
     *     {@link CertificationDetailsXMLImpl }
     *     
     */
    @Override
    public CertificationDetailsXMLImpl getCertification() {
        return certification;
    }

    /**
     * Sets the value of the certification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificationDetailsXMLImpl }
     *     
     */
    @Override
    public void setCertification(CertificationDetailsXMLImpl value) {
        this.certification = value;
    }

    /**
     * Gets the value of the contactPoint property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPointXMLImpl }
     *     
     */
    @Override
    public ContactPoint getContactPoint() {
        return contactPoint;
    }

    /**
     * Sets the value of the contactPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPointXMLImpl }
     *     
     */
    @Override
    public void setContactPoint(ContactPoint value) {
        this.contactPoint = value;
    }

    /**
     * Gets the value of the containedInPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public PlaceXMLImpl getContainedInPlace() {
        return containedInPlaceXMLImpl;
    }

    /**
     * Sets the value of the containedInPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public void setContainedInPlace(PlaceXMLImpl value) {
        this.containedInPlaceXMLImpl = value;
    }

    /**
     * Gets the value of the containsPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public PlaceXMLImpl getContainsPlace() {
        return containsPlaceXMLImpl;
    }

    /**
     * Sets the value of the containsPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public void setContainsPlace(PlaceXMLImpl value) {
        this.containsPlaceXMLImpl = value;
    }

    /**
     * Gets the value of the digitalAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getDigitalAddress() {
        return digitalAddress;
    }

    /**
     * Sets the value of the digitalAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setDigitalAddress(String value) {
        this.digitalAddress = value;
    }

    /**
     * Gets the value of the digitalLocationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getDigitalLocationName() {
        return digitalLocationName;
    }

    /**
     * Sets the value of the digitalLocationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setDigitalLocationName(String value) {
        this.digitalLocationName = value;
    }

    /**
     * Gets the value of the geo property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public PlaceXMLImpl getGeo() {
        return geo;
    }

    /**
     * Sets the value of the geo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public void setGeo(PlaceXMLImpl value) {
        this.geo = value;
    }

    /**
     * Gets the value of the glnType property.
     * 
     * @return
     *     possible object is
     *     {@link GLNTypeCode }
     *     
     */
    @Override
    public GLNTypeCode getGlnType() {
        return glnType;
    }

    /**
     * Sets the value of the glnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GLNTypeCode }
     *     
     */
    @Override
    public void setGlnType(GLNTypeCode value) {
        this.glnType = value;
    }

    /**
     * Gets the value of the globalLocationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getGlobalLocationNumber() {
        return globalLocationNumber;
    }

    /**
     * Sets the value of the globalLocationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setGlobalLocationNumber(String value) {
        this.globalLocationNumber = value;
    }

    /**
     * Gets the value of the leasedFrom property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getLeasedFrom() {
        return leasedFrom;
    }

    /**
     * Sets the value of the leasedFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setLeasedFrom(OrganizationXMLImpl value) {
        this.leasedFrom = value;
    }

    /**
     * Gets the value of the leasedTo property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getLeasedTo() {
        return leasedTo;
    }

    /**
     * Sets the value of the leasedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setLeasedTo(OrganizationXMLImpl value) {
        this.leasedTo = value;
    }

    /**
     * Gets the value of the locationGLN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getLocationGLN() {
        return locationGLN;
    }

    /**
     * Sets the value of the locationGLN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setLocationGLN(String value) {
        this.locationGLN = value;
    }

    /**
     * Gets the value of the locationHistory property.
     * 
     * @return
     *     possible object is
     *     {@link LocationStatusHistoryXMLImpl }
     *     
     */
    @Override
    public LocationStatusHistory getLocationHistory() {
        return locationHistory;
    }

    /**
     * Sets the value of the locationHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationStatusHistoryXMLImpl }
     *     
     */
    @Override
    public void setLocationHistory(LocationStatusHistory value) {
        this.locationHistory = value;
    }

    /**
     * Gets the value of the locationRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getLocationRole() {
        return locationRole;
    }

    /**
     * Sets the value of the locationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setLocationRole(String value) {
        this.locationRole = value;
    }

    /**
     * Gets the value of the managedBy property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getManagedBy() {
        return managedBy;
    }

    /**
     * Sets the value of the managedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setManagedBy(OrganizationXMLImpl value) {
        this.managedBy = value;
    }

    /**
     * Gets the value of the managedFor property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getManagedFor() {
        return managedFor;
    }

    /**
     * Sets the value of the managedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setManagedFor(OrganizationXMLImpl value) {
        this.managedFor = value;
    }

    /**
     * Gets the value of the occupiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getOccupiedBy() {
        return occupiedBy;
    }

    /**
     * Sets the value of the occupiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setOccupiedBy(OrganizationXMLImpl value) {
        this.occupiedBy = value;
    }

    /**
     * Gets the value of the ownedBy property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getOwnedBy() {
        return ownedBy;
    }

    /**
     * Sets the value of the ownedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setOwnedBy(OrganizationXMLImpl value) {
        this.ownedBy = value;
    }

    /**
     * Gets the value of the physicalLocationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
    public String getPhysicalLocationName() {
        return physicalLocationName;
    }

    /**
     * Sets the value of the physicalLocationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
    public void setPhysicalLocationName(String value) {
        this.physicalLocationName = value;
    }

    /**
     * Gets the value of the primaryLocationOf property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getPrimaryLocationOf() {
        return primaryLocationOf;
    }

    /**
     * Sets the value of the primaryLocationOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setPrimaryLocationOf(OrganizationXMLImpl value) {
        this.primaryLocationOf = value;
    }

    /**
     * Gets the value of the relatedOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getRelatedOrganization() {
        return relatedOrganizationXMLImpl;
    }

    /**
     * Sets the value of the relatedOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setRelatedOrganization(OrganizationXMLImpl value) {
        this.relatedOrganizationXMLImpl = value;
    }

    /**
     * Gets the value of the replacedByPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public PlaceXMLImpl getReplacedByPlace() {
        return replacedByPlaceXMLImpl;
    }

    /**
     * Sets the value of the replacedByPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public void setReplacedByPlace(PlaceXMLImpl value) {
        this.replacedByPlaceXMLImpl = value;
    }

    /**
     * Gets the value of the replacedPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public PlaceXMLImpl getReplacedPlace() {
        return replacedPlaceXMLImpl;
    }

    /**
     * Sets the value of the replacedPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceXMLImpl }
     *     
     */
    @Override
    public void setReplacedPlace(PlaceXMLImpl value) {
        this.replacedPlaceXMLImpl = value;
    }

    /**
     * Gets the value of the responsibleOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public OrganizationXMLImpl getResponsibleOrganization() {
        return responsibleOrganizationXMLImpl;
    }

    /**
     * Sets the value of the responsibleOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationXMLImpl }
     *     
     */
    @Override
    public void setResponsibleOrganization(OrganizationXMLImpl value) {
        this.responsibleOrganizationXMLImpl = value;
    }

}
