//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Product complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Product">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="additionalProductClassification" type="{}AdditionalProductClassificationDetails"/>
 *         <element name="additionalProductDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="additive" type="{}AdditiveDetails"/>
 *         <element name="audioFile" type="{}ReferencedFileDetails"/>
 *         <element name="authenticity" type="{}AuthenticityDetails"/>
 *         <element name="awardPrize" type="{}AwardPrizeDetails"/>
 *         <element name="bestBeforeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="brand" type="{}Brand"/>
 *         <element name="brandOwner" type="{}Organization"/>
 *         <element name="certification" type="{}CertificationDetails"/>
 *         <element name="colourCode" type="{}ColourCodeDetails"/>
 *         <element name="colourDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="consumerHandlingStorage" type="{}ReferencedFileDetails"/>
 *         <element name="consumerPackageDisclaimer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="consumerProductVariant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="consumerSafetyInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="consumerSalesCondition" type="{}ConsumerSalesConditionsCode"/>
 *         <element name="consumerStorageInstructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="consumerUsageInstructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="countryOfAssembly" type="{}Country"/>
 *         <element name="countryOfLastProcessing" type="{}Country"/>
 *         <element name="countryOfOrigin" type="{}Country"/>
 *         <element name="countryOfOriginStatement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="customerSupportCentre" type="{}Organization"/>
 *         <element name="dependentProprietaryProduct" type="{}Product"/>
 *         <element name="descriptiveSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="equivalentProduct" type="{}Product"/>
 *         <element name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="expirationDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="firstFreezeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="functionalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="gpcCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="gpcCategoryDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="grossArea" type="{}QuantitativeValue"/>
 *         <element name="grossVolume" type="{}QuantitativeValue"/>
 *         <element name="grossWeight" type="{}QuantitativeValue"/>
 *         <element name="growingMethod" type="{}GrowingMethodCode"/>
 *         <element name="gtin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="harvestDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="harvestDateEnd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="harvestDateStart" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="hasBatchLotNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="hasSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="hasThirdPartyControlledSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="healthClaimDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="image" type="{}ReferencedFileDetails"/>
 *         <element name="inPackageDepth" type="{}QuantitativeValue"/>
 *         <element name="inPackageDiameter" type="{}QuantitativeValue"/>
 *         <element name="inPackageHeight" type="{}QuantitativeValue"/>
 *         <element name="inPackageWidth" type="{}QuantitativeValue"/>
 *         <element name="includedAccessories" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="instructionsForUse" type="{}ReferencedFileDetails"/>
 *         <element name="isProductRecalled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="jws" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="manufacturer" type="{}Organization"/>
 *         <element name="manufacturersWarranty" type="{}WarrantyPromise"/>
 *         <element name="manufacturingPlant" type="{}Organization"/>
 *         <element name="massPerUnitArea" type="{}QuantitativeValue"/>
 *         <element name="netArea" type="{}QuantitativeValue"/>
 *         <element name="netContent" type="{}QuantitativeValue"/>
 *         <element name="netWeight" type="{}QuantitativeValue"/>
 *         <element name="organicClaim" type="{}OrganicClaimDetails"/>
 *         <element name="outOfPackageDepth" type="{}QuantitativeValue"/>
 *         <element name="outOfPackageDiameter" type="{}QuantitativeValue"/>
 *         <element name="outOfPackageHeight" type="{}QuantitativeValue"/>
 *         <element name="outOfPackageWidth" type="{}QuantitativeValue"/>
 *         <element name="packaging" type="{}PackagingDetails"/>
 *         <element name="packagingDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="packagingMarkedLabelAccreditation" type="{}PackagingMarkedLabelAccreditationCode"/>
 *         <element name="primaryAlternateProduct" type="{}Product"/>
 *         <element name="productDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productFeatureBenefit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productFormDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productMarketingMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productSustainabilityInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productionDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productionDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productionVariantDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="productionVariantEffectiveDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="provenanceStatement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="referencedFile" type="{}ReferencedFileDetails"/>
 *         <element name="regulatedProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="replacedByProduct" type="{}Product"/>
 *         <element name="replacedProduct" type="{}Product"/>
 *         <element name="sellByDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="sizeCode" type="{}SizeCodeDetails"/>
 *         <element name="supplierSpecifiedMinimumConsumerStorageDays" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="targetMarket" type="{}TargetMarketDetails"/>
 *         <element name="variantDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="warningCopyDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "additionalProductClassification",
    "additionalProductDescription",
    "additive",
    "audioFile",
    "authenticity",
    "awardPrize",
    "bestBeforeDate",
    "brand",
    "brandOwner",
    "certification",
    "colourCode",
    "colourDescription",
    "consumerHandlingStorage",
    "consumerPackageDisclaimer",
    "consumerProductVariant",
    "consumerSafetyInformation",
    "consumerSalesCondition",
    "consumerStorageInstructions",
    "consumerUsageInstructions",
    "countryOfAssembly",
    "countryOfLastProcessing",
    "countryOfOrigin",
    "countryOfOriginStatement",
    "customerSupportCentre",
    "dependentProprietaryProduct",
    "descriptiveSize",
    "dueDate",
    "equivalentProduct",
    "expirationDate",
    "expirationDateTime",
    "firstFreezeDate",
    "functionalName",
    "gpcCategoryCode",
    "gpcCategoryDescription",
    "grossArea",
    "grossVolume",
    "grossWeight",
    "growingMethod",
    "gtin",
    "harvestDate",
    "harvestDateEnd",
    "harvestDateStart",
    "hasBatchLotNumber",
    "hasSerialNumber",
    "hasThirdPartyControlledSerialNumber",
    "healthClaimDescription",
    "image",
    "inPackageDepth",
    "inPackageDiameter",
    "inPackageHeight",
    "inPackageWidth",
    "includedAccessories",
    "instructionsForUse",
    "isProductRecalled",
    "jws",
    "manufacturer",
    "manufacturersWarranty",
    "manufacturingPlant",
    "massPerUnitArea",
    "netArea",
    "netContent",
    "netWeight",
    "organicClaim",
    "outOfPackageDepth",
    "outOfPackageDiameter",
    "outOfPackageHeight",
    "outOfPackageWidth",
    "packaging",
    "packagingDate",
    "packagingMarkedLabelAccreditation",
    "primaryAlternateProduct",
    "productDescription",
    "productFeatureBenefit",
    "productFormDescription",
    "productID",
    "productMarketingMessage",
    "productName",
    "productRange",
    "productSustainabilityInfo",
    "productionDate",
    "productionDateTime",
    "productionVariantDescription",
    "productionVariantEffectiveDateTime",
    "provenanceStatement",
    "referencedFile",
    "regulatedProductName",
    "replacedByProduct",
    "replacedProduct",
    "sellByDate",
    "sizeCode",
    "supplierSpecifiedMinimumConsumerStorageDays",
    "targetMarket",
    "variantDescription",
    "warningCopyDescription"
})
@XmlSeeAlso({
    FoodBeverageTobaccoProduct.class,
    WearableProduct.class
})
public class Product {

    @XmlElement(required = true)
    protected AdditionalProductClassificationDetails additionalProductClassification;
    @XmlElement(required = true)
    protected String additionalProductDescription;
    @XmlElement(required = true)
    protected AdditiveDetails additive;
    @XmlElement(required = true)
    protected ReferencedFileDetails audioFile;
    @XmlElement(required = true)
    protected AuthenticityDetails authenticity;
    @XmlElement(required = true)
    protected AwardPrizeDetails awardPrize;
    @XmlElement(required = true)
    protected String bestBeforeDate;
    @XmlElement(required = true)
    protected Brand brand;
    @XmlElement(required = true)
    protected Organization brandOwner;
    @XmlElement(required = true)
    protected CertificationDetails certification;
    @XmlElement(required = true)
    protected ColourCodeDetails colourCode;
    @XmlElement(required = true)
    protected String colourDescription;
    @XmlElement(required = true)
    protected ReferencedFileDetails consumerHandlingStorage;
    @XmlElement(required = true)
    protected String consumerPackageDisclaimer;
    @XmlElement(required = true)
    protected String consumerProductVariant;
    @XmlElement(required = true)
    protected String consumerSafetyInformation;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ConsumerSalesConditionsCode consumerSalesCondition;
    @XmlElement(required = true)
    protected String consumerStorageInstructions;
    @XmlElement(required = true)
    protected String consumerUsageInstructions;
    @XmlElement(required = true)
    protected Country countryOfAssembly;
    @XmlElement(required = true)
    protected Country countryOfLastProcessing;
    @XmlElement(required = true)
    protected Country countryOfOrigin;
    @XmlElement(required = true)
    protected String countryOfOriginStatement;
    @XmlElement(required = true)
    protected Organization customerSupportCentre;
    @XmlElement(required = true)
    protected Product dependentProprietaryProduct;
    @XmlElement(required = true)
    protected String descriptiveSize;
    @XmlElement(required = true)
    protected String dueDate;
    @XmlElement(required = true)
    protected Product equivalentProduct;
    @XmlElement(required = true)
    protected String expirationDate;
    @XmlElement(required = true)
    protected String expirationDateTime;
    @XmlElement(required = true)
    protected String firstFreezeDate;
    @XmlElement(required = true)
    protected String functionalName;
    @XmlElement(required = true)
    protected String gpcCategoryCode;
    @XmlElement(required = true)
    protected String gpcCategoryDescription;
    @XmlElement(required = true)
    protected QuantitativeValue grossArea;
    @XmlElement(required = true)
    protected QuantitativeValue grossVolume;
    @XmlElement(required = true)
    protected QuantitativeValue grossWeight;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected GrowingMethodCode growingMethod;
    @XmlElement(required = true)
    protected String gtin;
    @XmlElement(required = true)
    protected String harvestDate;
    @XmlElement(required = true)
    protected String harvestDateEnd;
    @XmlElement(required = true)
    protected String harvestDateStart;
    @XmlElement(required = true)
    protected String hasBatchLotNumber;
    @XmlElement(required = true)
    protected String hasSerialNumber;
    @XmlElement(required = true)
    protected String hasThirdPartyControlledSerialNumber;
    @XmlElement(required = true)
    protected String healthClaimDescription;
    @XmlElement(required = true)
    protected ReferencedFileDetails image;
    @XmlElement(required = true)
    protected QuantitativeValue inPackageDepth;
    @XmlElement(required = true)
    protected QuantitativeValue inPackageDiameter;
    @XmlElement(required = true)
    protected QuantitativeValue inPackageHeight;
    @XmlElement(required = true)
    protected QuantitativeValue inPackageWidth;
    @XmlElement(required = true)
    protected String includedAccessories;
    @XmlElement(required = true)
    protected ReferencedFileDetails instructionsForUse;
    @XmlElement(required = true)
    protected String isProductRecalled;
    @XmlElement(required = true)
    protected String jws;
    @XmlElement(required = true)
    protected Organization manufacturer;
    @XmlElement(required = true)
    protected WarrantyPromise manufacturersWarranty;
    @XmlElement(required = true)
    protected Organization manufacturingPlant;
    @XmlElement(required = true)
    protected QuantitativeValue massPerUnitArea;
    @XmlElement(required = true)
    protected QuantitativeValue netArea;
    @XmlElement(required = true)
    protected QuantitativeValue netContent;
    @XmlElement(required = true)
    protected QuantitativeValue netWeight;
    @XmlElement(required = true)
    protected OrganicClaimDetails organicClaim;
    @XmlElement(required = true)
    protected QuantitativeValue outOfPackageDepth;
    @XmlElement(required = true)
    protected QuantitativeValue outOfPackageDiameter;
    @XmlElement(required = true)
    protected QuantitativeValue outOfPackageHeight;
    @XmlElement(required = true)
    protected QuantitativeValue outOfPackageWidth;
    @XmlElement(required = true)
    protected PackagingDetails packaging;
    @XmlElement(required = true)
    protected String packagingDate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PackagingMarkedLabelAccreditationCode packagingMarkedLabelAccreditation;
    @XmlElement(required = true)
    protected Product primaryAlternateProduct;
    @XmlElement(required = true)
    protected String productDescription;
    @XmlElement(required = true)
    protected String productFeatureBenefit;
    @XmlElement(required = true)
    protected String productFormDescription;
    @XmlElement(required = true)
    protected String productID;
    @XmlElement(required = true)
    protected String productMarketingMessage;
    @XmlElement(required = true)
    protected String productName;
    @XmlElement(required = true)
    protected String productRange;
    @XmlElement(required = true)
    protected String productSustainabilityInfo;
    @XmlElement(required = true)
    protected String productionDate;
    @XmlElement(required = true)
    protected String productionDateTime;
    @XmlElement(required = true)
    protected String productionVariantDescription;
    @XmlElement(required = true)
    protected String productionVariantEffectiveDateTime;
    @XmlElement(required = true)
    protected String provenanceStatement;
    @XmlElement(required = true)
    protected ReferencedFileDetails referencedFile;
    @XmlElement(required = true)
    protected String regulatedProductName;
    @XmlElement(required = true)
    protected Product replacedByProduct;
    @XmlElement(required = true)
    protected Product replacedProduct;
    @XmlElement(required = true)
    protected String sellByDate;
    @XmlElement(required = true)
    protected SizeCodeDetails sizeCode;
    @XmlElement(required = true)
    protected String supplierSpecifiedMinimumConsumerStorageDays;
    @XmlElement(required = true)
    protected TargetMarketDetails targetMarket;
    @XmlElement(required = true)
    protected String variantDescription;
    @XmlElement(required = true)
    protected String warningCopyDescription;

    /**
     * Gets the value of the additionalProductClassification property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalProductClassificationDetails }
     *     
     */
    public AdditionalProductClassificationDetails getAdditionalProductClassification() {
        return additionalProductClassification;
    }

    /**
     * Sets the value of the additionalProductClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalProductClassificationDetails }
     *     
     */
    public void setAdditionalProductClassification(AdditionalProductClassificationDetails value) {
        this.additionalProductClassification = value;
    }

    /**
     * Gets the value of the additionalProductDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalProductDescription() {
        return additionalProductDescription;
    }

    /**
     * Sets the value of the additionalProductDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalProductDescription(String value) {
        this.additionalProductDescription = value;
    }

    /**
     * Gets the value of the additive property.
     * 
     * @return
     *     possible object is
     *     {@link AdditiveDetails }
     *     
     */
    public AdditiveDetails getAdditive() {
        return additive;
    }

    /**
     * Sets the value of the additive property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditiveDetails }
     *     
     */
    public void setAdditive(AdditiveDetails value) {
        this.additive = value;
    }

    /**
     * Gets the value of the audioFile property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public ReferencedFileDetails getAudioFile() {
        return audioFile;
    }

    /**
     * Sets the value of the audioFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public void setAudioFile(ReferencedFileDetails value) {
        this.audioFile = value;
    }

    /**
     * Gets the value of the authenticity property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticityDetails }
     *     
     */
    public AuthenticityDetails getAuthenticity() {
        return authenticity;
    }

    /**
     * Sets the value of the authenticity property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticityDetails }
     *     
     */
    public void setAuthenticity(AuthenticityDetails value) {
        this.authenticity = value;
    }

    /**
     * Gets the value of the awardPrize property.
     * 
     * @return
     *     possible object is
     *     {@link AwardPrizeDetails }
     *     
     */
    public AwardPrizeDetails getAwardPrize() {
        return awardPrize;
    }

    /**
     * Sets the value of the awardPrize property.
     * 
     * @param value
     *     allowed object is
     *     {@link AwardPrizeDetails }
     *     
     */
    public void setAwardPrize(AwardPrizeDetails value) {
        this.awardPrize = value;
    }

    /**
     * Gets the value of the bestBeforeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBestBeforeDate() {
        return bestBeforeDate;
    }

    /**
     * Sets the value of the bestBeforeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBestBeforeDate(String value) {
        this.bestBeforeDate = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link Brand }
     *     
     */
    public Brand getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Brand }
     *     
     */
    public void setBrand(Brand value) {
        this.brand = value;
    }

    /**
     * Gets the value of the brandOwner property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getBrandOwner() {
        return brandOwner;
    }

    /**
     * Sets the value of the brandOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setBrandOwner(Organization value) {
        this.brandOwner = value;
    }

    /**
     * Gets the value of the certification property.
     * 
     * @return
     *     possible object is
     *     {@link CertificationDetails }
     *     
     */
    public CertificationDetails getCertification() {
        return certification;
    }

    /**
     * Sets the value of the certification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CertificationDetails }
     *     
     */
    public void setCertification(CertificationDetails value) {
        this.certification = value;
    }

    /**
     * Gets the value of the colourCode property.
     * 
     * @return
     *     possible object is
     *     {@link ColourCodeDetails }
     *     
     */
    public ColourCodeDetails getColourCode() {
        return colourCode;
    }

    /**
     * Sets the value of the colourCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColourCodeDetails }
     *     
     */
    public void setColourCode(ColourCodeDetails value) {
        this.colourCode = value;
    }

    /**
     * Gets the value of the colourDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColourDescription() {
        return colourDescription;
    }

    /**
     * Sets the value of the colourDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColourDescription(String value) {
        this.colourDescription = value;
    }

    /**
     * Gets the value of the consumerHandlingStorage property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public ReferencedFileDetails getConsumerHandlingStorage() {
        return consumerHandlingStorage;
    }

    /**
     * Sets the value of the consumerHandlingStorage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public void setConsumerHandlingStorage(ReferencedFileDetails value) {
        this.consumerHandlingStorage = value;
    }

    /**
     * Gets the value of the consumerPackageDisclaimer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerPackageDisclaimer() {
        return consumerPackageDisclaimer;
    }

    /**
     * Sets the value of the consumerPackageDisclaimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerPackageDisclaimer(String value) {
        this.consumerPackageDisclaimer = value;
    }

    /**
     * Gets the value of the consumerProductVariant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerProductVariant() {
        return consumerProductVariant;
    }

    /**
     * Sets the value of the consumerProductVariant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerProductVariant(String value) {
        this.consumerProductVariant = value;
    }

    /**
     * Gets the value of the consumerSafetyInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerSafetyInformation() {
        return consumerSafetyInformation;
    }

    /**
     * Sets the value of the consumerSafetyInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerSafetyInformation(String value) {
        this.consumerSafetyInformation = value;
    }

    /**
     * Gets the value of the consumerSalesCondition property.
     * 
     * @return
     *     possible object is
     *     {@link ConsumerSalesConditionsCode }
     *     
     */
    public ConsumerSalesConditionsCode getConsumerSalesCondition() {
        return consumerSalesCondition;
    }

    /**
     * Sets the value of the consumerSalesCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsumerSalesConditionsCode }
     *     
     */
    public void setConsumerSalesCondition(ConsumerSalesConditionsCode value) {
        this.consumerSalesCondition = value;
    }

    /**
     * Gets the value of the consumerStorageInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerStorageInstructions() {
        return consumerStorageInstructions;
    }

    /**
     * Sets the value of the consumerStorageInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerStorageInstructions(String value) {
        this.consumerStorageInstructions = value;
    }

    /**
     * Gets the value of the consumerUsageInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerUsageInstructions() {
        return consumerUsageInstructions;
    }

    /**
     * Sets the value of the consumerUsageInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerUsageInstructions(String value) {
        this.consumerUsageInstructions = value;
    }

    /**
     * Gets the value of the countryOfAssembly property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountryOfAssembly() {
        return countryOfAssembly;
    }

    /**
     * Sets the value of the countryOfAssembly property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountryOfAssembly(Country value) {
        this.countryOfAssembly = value;
    }

    /**
     * Gets the value of the countryOfLastProcessing property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountryOfLastProcessing() {
        return countryOfLastProcessing;
    }

    /**
     * Sets the value of the countryOfLastProcessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountryOfLastProcessing(Country value) {
        this.countryOfLastProcessing = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link Country }
     *     
     */
    public Country getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Country }
     *     
     */
    public void setCountryOfOrigin(Country value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the countryOfOriginStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOriginStatement() {
        return countryOfOriginStatement;
    }

    /**
     * Sets the value of the countryOfOriginStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOriginStatement(String value) {
        this.countryOfOriginStatement = value;
    }

    /**
     * Gets the value of the customerSupportCentre property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getCustomerSupportCentre() {
        return customerSupportCentre;
    }

    /**
     * Sets the value of the customerSupportCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setCustomerSupportCentre(Organization value) {
        this.customerSupportCentre = value;
    }

    /**
     * Gets the value of the dependentProprietaryProduct property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getDependentProprietaryProduct() {
        return dependentProprietaryProduct;
    }

    /**
     * Sets the value of the dependentProprietaryProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setDependentProprietaryProduct(Product value) {
        this.dependentProprietaryProduct = value;
    }

    /**
     * Gets the value of the descriptiveSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptiveSize() {
        return descriptiveSize;
    }

    /**
     * Sets the value of the descriptiveSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptiveSize(String value) {
        this.descriptiveSize = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the equivalentProduct property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getEquivalentProduct() {
        return equivalentProduct;
    }

    /**
     * Sets the value of the equivalentProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setEquivalentProduct(Product value) {
        this.equivalentProduct = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDate(String value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the expirationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirationDateTime() {
        return expirationDateTime;
    }

    /**
     * Sets the value of the expirationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirationDateTime(String value) {
        this.expirationDateTime = value;
    }

    /**
     * Gets the value of the firstFreezeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstFreezeDate() {
        return firstFreezeDate;
    }

    /**
     * Sets the value of the firstFreezeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstFreezeDate(String value) {
        this.firstFreezeDate = value;
    }

    /**
     * Gets the value of the functionalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunctionalName() {
        return functionalName;
    }

    /**
     * Sets the value of the functionalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunctionalName(String value) {
        this.functionalName = value;
    }

    /**
     * Gets the value of the gpcCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpcCategoryCode() {
        return gpcCategoryCode;
    }

    /**
     * Sets the value of the gpcCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpcCategoryCode(String value) {
        this.gpcCategoryCode = value;
    }

    /**
     * Gets the value of the gpcCategoryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGpcCategoryDescription() {
        return gpcCategoryDescription;
    }

    /**
     * Sets the value of the gpcCategoryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGpcCategoryDescription(String value) {
        this.gpcCategoryDescription = value;
    }

    /**
     * Gets the value of the grossArea property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getGrossArea() {
        return grossArea;
    }

    /**
     * Sets the value of the grossArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setGrossArea(QuantitativeValue value) {
        this.grossArea = value;
    }

    /**
     * Gets the value of the grossVolume property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getGrossVolume() {
        return grossVolume;
    }

    /**
     * Sets the value of the grossVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setGrossVolume(QuantitativeValue value) {
        this.grossVolume = value;
    }

    /**
     * Gets the value of the grossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getGrossWeight() {
        return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setGrossWeight(QuantitativeValue value) {
        this.grossWeight = value;
    }

    /**
     * Gets the value of the growingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link GrowingMethodCode }
     *     
     */
    public GrowingMethodCode getGrowingMethod() {
        return growingMethod;
    }

    /**
     * Sets the value of the growingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link GrowingMethodCode }
     *     
     */
    public void setGrowingMethod(GrowingMethodCode value) {
        this.growingMethod = value;
    }

    /**
     * Gets the value of the gtin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGtin() {
        return gtin;
    }

    /**
     * Sets the value of the gtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGtin(String value) {
        this.gtin = value;
    }

    /**
     * Gets the value of the harvestDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarvestDate() {
        return harvestDate;
    }

    /**
     * Sets the value of the harvestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarvestDate(String value) {
        this.harvestDate = value;
    }

    /**
     * Gets the value of the harvestDateEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarvestDateEnd() {
        return harvestDateEnd;
    }

    /**
     * Sets the value of the harvestDateEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarvestDateEnd(String value) {
        this.harvestDateEnd = value;
    }

    /**
     * Gets the value of the harvestDateStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarvestDateStart() {
        return harvestDateStart;
    }

    /**
     * Sets the value of the harvestDateStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarvestDateStart(String value) {
        this.harvestDateStart = value;
    }

    /**
     * Gets the value of the hasBatchLotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasBatchLotNumber() {
        return hasBatchLotNumber;
    }

    /**
     * Sets the value of the hasBatchLotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasBatchLotNumber(String value) {
        this.hasBatchLotNumber = value;
    }

    /**
     * Gets the value of the hasSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasSerialNumber() {
        return hasSerialNumber;
    }

    /**
     * Sets the value of the hasSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasSerialNumber(String value) {
        this.hasSerialNumber = value;
    }

    /**
     * Gets the value of the hasThirdPartyControlledSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasThirdPartyControlledSerialNumber() {
        return hasThirdPartyControlledSerialNumber;
    }

    /**
     * Sets the value of the hasThirdPartyControlledSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasThirdPartyControlledSerialNumber(String value) {
        this.hasThirdPartyControlledSerialNumber = value;
    }

    /**
     * Gets the value of the healthClaimDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHealthClaimDescription() {
        return healthClaimDescription;
    }

    /**
     * Sets the value of the healthClaimDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHealthClaimDescription(String value) {
        this.healthClaimDescription = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public ReferencedFileDetails getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public void setImage(ReferencedFileDetails value) {
        this.image = value;
    }

    /**
     * Gets the value of the inPackageDepth property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getInPackageDepth() {
        return inPackageDepth;
    }

    /**
     * Sets the value of the inPackageDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setInPackageDepth(QuantitativeValue value) {
        this.inPackageDepth = value;
    }

    /**
     * Gets the value of the inPackageDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getInPackageDiameter() {
        return inPackageDiameter;
    }

    /**
     * Sets the value of the inPackageDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setInPackageDiameter(QuantitativeValue value) {
        this.inPackageDiameter = value;
    }

    /**
     * Gets the value of the inPackageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getInPackageHeight() {
        return inPackageHeight;
    }

    /**
     * Sets the value of the inPackageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setInPackageHeight(QuantitativeValue value) {
        this.inPackageHeight = value;
    }

    /**
     * Gets the value of the inPackageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getInPackageWidth() {
        return inPackageWidth;
    }

    /**
     * Sets the value of the inPackageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setInPackageWidth(QuantitativeValue value) {
        this.inPackageWidth = value;
    }

    /**
     * Gets the value of the includedAccessories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludedAccessories() {
        return includedAccessories;
    }

    /**
     * Sets the value of the includedAccessories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludedAccessories(String value) {
        this.includedAccessories = value;
    }

    /**
     * Gets the value of the instructionsForUse property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public ReferencedFileDetails getInstructionsForUse() {
        return instructionsForUse;
    }

    /**
     * Sets the value of the instructionsForUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public void setInstructionsForUse(ReferencedFileDetails value) {
        this.instructionsForUse = value;
    }

    /**
     * Gets the value of the isProductRecalled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsProductRecalled() {
        return isProductRecalled;
    }

    /**
     * Sets the value of the isProductRecalled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsProductRecalled(String value) {
        this.isProductRecalled = value;
    }

    /**
     * Gets the value of the jws property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJws() {
        return jws;
    }

    /**
     * Sets the value of the jws property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJws(String value) {
        this.jws = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setManufacturer(Organization value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the manufacturersWarranty property.
     * 
     * @return
     *     possible object is
     *     {@link WarrantyPromise }
     *     
     */
    public WarrantyPromise getManufacturersWarranty() {
        return manufacturersWarranty;
    }

    /**
     * Sets the value of the manufacturersWarranty property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarrantyPromise }
     *     
     */
    public void setManufacturersWarranty(WarrantyPromise value) {
        this.manufacturersWarranty = value;
    }

    /**
     * Gets the value of the manufacturingPlant property.
     * 
     * @return
     *     possible object is
     *     {@link Organization }
     *     
     */
    public Organization getManufacturingPlant() {
        return manufacturingPlant;
    }

    /**
     * Sets the value of the manufacturingPlant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organization }
     *     
     */
    public void setManufacturingPlant(Organization value) {
        this.manufacturingPlant = value;
    }

    /**
     * Gets the value of the massPerUnitArea property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getMassPerUnitArea() {
        return massPerUnitArea;
    }

    /**
     * Sets the value of the massPerUnitArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setMassPerUnitArea(QuantitativeValue value) {
        this.massPerUnitArea = value;
    }

    /**
     * Gets the value of the netArea property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getNetArea() {
        return netArea;
    }

    /**
     * Sets the value of the netArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setNetArea(QuantitativeValue value) {
        this.netArea = value;
    }

    /**
     * Gets the value of the netContent property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getNetContent() {
        return netContent;
    }

    /**
     * Sets the value of the netContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setNetContent(QuantitativeValue value) {
        this.netContent = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getNetWeight() {
        return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setNetWeight(QuantitativeValue value) {
        this.netWeight = value;
    }

    /**
     * Gets the value of the organicClaim property.
     * 
     * @return
     *     possible object is
     *     {@link OrganicClaimDetails }
     *     
     */
    public OrganicClaimDetails getOrganicClaim() {
        return organicClaim;
    }

    /**
     * Sets the value of the organicClaim property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganicClaimDetails }
     *     
     */
    public void setOrganicClaim(OrganicClaimDetails value) {
        this.organicClaim = value;
    }

    /**
     * Gets the value of the outOfPackageDepth property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getOutOfPackageDepth() {
        return outOfPackageDepth;
    }

    /**
     * Sets the value of the outOfPackageDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setOutOfPackageDepth(QuantitativeValue value) {
        this.outOfPackageDepth = value;
    }

    /**
     * Gets the value of the outOfPackageDiameter property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getOutOfPackageDiameter() {
        return outOfPackageDiameter;
    }

    /**
     * Sets the value of the outOfPackageDiameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setOutOfPackageDiameter(QuantitativeValue value) {
        this.outOfPackageDiameter = value;
    }

    /**
     * Gets the value of the outOfPackageHeight property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getOutOfPackageHeight() {
        return outOfPackageHeight;
    }

    /**
     * Sets the value of the outOfPackageHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setOutOfPackageHeight(QuantitativeValue value) {
        this.outOfPackageHeight = value;
    }

    /**
     * Gets the value of the outOfPackageWidth property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getOutOfPackageWidth() {
        return outOfPackageWidth;
    }

    /**
     * Sets the value of the outOfPackageWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setOutOfPackageWidth(QuantitativeValue value) {
        this.outOfPackageWidth = value;
    }

    /**
     * Gets the value of the packaging property.
     * 
     * @return
     *     possible object is
     *     {@link PackagingDetails }
     *     
     */
    public PackagingDetails getPackaging() {
        return packaging;
    }

    /**
     * Sets the value of the packaging property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagingDetails }
     *     
     */
    public void setPackaging(PackagingDetails value) {
        this.packaging = value;
    }

    /**
     * Gets the value of the packagingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackagingDate() {
        return packagingDate;
    }

    /**
     * Sets the value of the packagingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackagingDate(String value) {
        this.packagingDate = value;
    }

    /**
     * Gets the value of the packagingMarkedLabelAccreditation property.
     * 
     * @return
     *     possible object is
     *     {@link PackagingMarkedLabelAccreditationCode }
     *     
     */
    public PackagingMarkedLabelAccreditationCode getPackagingMarkedLabelAccreditation() {
        return packagingMarkedLabelAccreditation;
    }

    /**
     * Sets the value of the packagingMarkedLabelAccreditation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagingMarkedLabelAccreditationCode }
     *     
     */
    public void setPackagingMarkedLabelAccreditation(PackagingMarkedLabelAccreditationCode value) {
        this.packagingMarkedLabelAccreditation = value;
    }

    /**
     * Gets the value of the primaryAlternateProduct property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getPrimaryAlternateProduct() {
        return primaryAlternateProduct;
    }

    /**
     * Sets the value of the primaryAlternateProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setPrimaryAlternateProduct(Product value) {
        this.primaryAlternateProduct = value;
    }

    /**
     * Gets the value of the productDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * Sets the value of the productDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDescription(String value) {
        this.productDescription = value;
    }

    /**
     * Gets the value of the productFeatureBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductFeatureBenefit() {
        return productFeatureBenefit;
    }

    /**
     * Sets the value of the productFeatureBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductFeatureBenefit(String value) {
        this.productFeatureBenefit = value;
    }

    /**
     * Gets the value of the productFormDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductFormDescription() {
        return productFormDescription;
    }

    /**
     * Sets the value of the productFormDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductFormDescription(String value) {
        this.productFormDescription = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductID(String value) {
        this.productID = value;
    }

    /**
     * Gets the value of the productMarketingMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductMarketingMessage() {
        return productMarketingMessage;
    }

    /**
     * Sets the value of the productMarketingMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductMarketingMessage(String value) {
        this.productMarketingMessage = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductRange() {
        return productRange;
    }

    /**
     * Sets the value of the productRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductRange(String value) {
        this.productRange = value;
    }

    /**
     * Gets the value of the productSustainabilityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductSustainabilityInfo() {
        return productSustainabilityInfo;
    }

    /**
     * Sets the value of the productSustainabilityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductSustainabilityInfo(String value) {
        this.productSustainabilityInfo = value;
    }

    /**
     * Gets the value of the productionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionDate() {
        return productionDate;
    }

    /**
     * Sets the value of the productionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionDate(String value) {
        this.productionDate = value;
    }

    /**
     * Gets the value of the productionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionDateTime() {
        return productionDateTime;
    }

    /**
     * Sets the value of the productionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionDateTime(String value) {
        this.productionDateTime = value;
    }

    /**
     * Gets the value of the productionVariantDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionVariantDescription() {
        return productionVariantDescription;
    }

    /**
     * Sets the value of the productionVariantDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionVariantDescription(String value) {
        this.productionVariantDescription = value;
    }

    /**
     * Gets the value of the productionVariantEffectiveDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductionVariantEffectiveDateTime() {
        return productionVariantEffectiveDateTime;
    }

    /**
     * Sets the value of the productionVariantEffectiveDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductionVariantEffectiveDateTime(String value) {
        this.productionVariantEffectiveDateTime = value;
    }

    /**
     * Gets the value of the provenanceStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvenanceStatement() {
        return provenanceStatement;
    }

    /**
     * Sets the value of the provenanceStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvenanceStatement(String value) {
        this.provenanceStatement = value;
    }

    /**
     * Gets the value of the referencedFile property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public ReferencedFileDetails getReferencedFile() {
        return referencedFile;
    }

    /**
     * Sets the value of the referencedFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencedFileDetails }
     *     
     */
    public void setReferencedFile(ReferencedFileDetails value) {
        this.referencedFile = value;
    }

    /**
     * Gets the value of the regulatedProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegulatedProductName() {
        return regulatedProductName;
    }

    /**
     * Sets the value of the regulatedProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegulatedProductName(String value) {
        this.regulatedProductName = value;
    }

    /**
     * Gets the value of the replacedByProduct property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getReplacedByProduct() {
        return replacedByProduct;
    }

    /**
     * Sets the value of the replacedByProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setReplacedByProduct(Product value) {
        this.replacedByProduct = value;
    }

    /**
     * Gets the value of the replacedProduct property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getReplacedProduct() {
        return replacedProduct;
    }

    /**
     * Sets the value of the replacedProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setReplacedProduct(Product value) {
        this.replacedProduct = value;
    }

    /**
     * Gets the value of the sellByDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSellByDate() {
        return sellByDate;
    }

    /**
     * Sets the value of the sellByDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSellByDate(String value) {
        this.sellByDate = value;
    }

    /**
     * Gets the value of the sizeCode property.
     * 
     * @return
     *     possible object is
     *     {@link SizeCodeDetails }
     *     
     */
    public SizeCodeDetails getSizeCode() {
        return sizeCode;
    }

    /**
     * Sets the value of the sizeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeCodeDetails }
     *     
     */
    public void setSizeCode(SizeCodeDetails value) {
        this.sizeCode = value;
    }

    /**
     * Gets the value of the supplierSpecifiedMinimumConsumerStorageDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierSpecifiedMinimumConsumerStorageDays() {
        return supplierSpecifiedMinimumConsumerStorageDays;
    }

    /**
     * Sets the value of the supplierSpecifiedMinimumConsumerStorageDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierSpecifiedMinimumConsumerStorageDays(String value) {
        this.supplierSpecifiedMinimumConsumerStorageDays = value;
    }

    /**
     * Gets the value of the targetMarket property.
     * 
     * @return
     *     possible object is
     *     {@link TargetMarketDetails }
     *     
     */
    public TargetMarketDetails getTargetMarket() {
        return targetMarket;
    }

    /**
     * Sets the value of the targetMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetMarketDetails }
     *     
     */
    public void setTargetMarket(TargetMarketDetails value) {
        this.targetMarket = value;
    }

    /**
     * Gets the value of the variantDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariantDescription() {
        return variantDescription;
    }

    /**
     * Sets the value of the variantDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariantDescription(String value) {
        this.variantDescription = value;
    }

    /**
     * Gets the value of the warningCopyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarningCopyDescription() {
        return warningCopyDescription;
    }

    /**
     * Sets the value of the warningCopyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarningCopyDescription(String value) {
        this.warningCopyDescription = value;
    }

}
