//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for Seafood complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="Seafood">
 *   <complexContent>
 *     <extension base="{}FoodBeverageTobaccoProduct">
 *       <sequence>
 *         <element name="catchZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="fishType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="freshOrSeawaterFarmed" type="{}FreshOrSeawaterFarmedCode"/>
 *         <element name="minimumFishContent" type="{}QuantitativeValue"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Seafood", propOrder = {
    "catchZone",
    "fishType",
    "freshOrSeawaterFarmed",
    "minimumFishContent"
})
public class Seafood
    extends FoodBeverageTobaccoProduct
{

    @XmlElement(required = true)
    protected String catchZone;
    @XmlElement(required = true)
    protected String fishType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected FreshOrSeawaterFarmedCode freshOrSeawaterFarmed;
    @XmlElement(required = true)
    protected QuantitativeValue minimumFishContent;

    /**
     * Gets the value of the catchZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatchZone() {
        return catchZone;
    }

    /**
     * Sets the value of the catchZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatchZone(String value) {
        this.catchZone = value;
    }

    /**
     * Gets the value of the fishType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFishType() {
        return fishType;
    }

    /**
     * Sets the value of the fishType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFishType(String value) {
        this.fishType = value;
    }

    /**
     * Gets the value of the freshOrSeawaterFarmed property.
     * 
     * @return
     *     possible object is
     *     {@link FreshOrSeawaterFarmedCode }
     *     
     */
    public FreshOrSeawaterFarmedCode getFreshOrSeawaterFarmed() {
        return freshOrSeawaterFarmed;
    }

    /**
     * Sets the value of the freshOrSeawaterFarmed property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreshOrSeawaterFarmedCode }
     *     
     */
    public void setFreshOrSeawaterFarmed(FreshOrSeawaterFarmedCode value) {
        this.freshOrSeawaterFarmed = value;
    }

    /**
     * Gets the value of the minimumFishContent property.
     * 
     * @return
     *     possible object is
     *     {@link QuantitativeValue }
     *     
     */
    public QuantitativeValue getMinimumFishContent() {
        return minimumFishContent;
    }

    /**
     * Sets the value of the minimumFishContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantitativeValue }
     *     
     */
    public void setMinimumFishContent(QuantitativeValue value) {
        this.minimumFishContent = value;
    }

}
