//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for SecurityMarking.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="SecurityMarking">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="HOLOGRAM"/>
 *     <enumeration value="MICROPRINTING"/>
 *     <enumeration value="UVINK"/>
 *     <enumeration value="WATERMARK"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "SecurityMarking")
@XmlEnum
public enum SecurityMarking {
  HOLOGRAM,
  MICROPRINTING,
  UVINK,
  WATERMARK;

  public String value() {
    return name();
  }

  public static SecurityMarking fromValue(String v) {
    return valueOf(v);
  }
}
