//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.SizeDetails;
import jakarta.xml.bind.annotation.*;

/**
 * A grouping of properties related to the size of a wearable product
 *
 * <p>Java class for SizeDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="SizeDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="sizeDimension" type="{}QuantitativeValue"/>
 *         <element name="sizeGroup" type="{}SizeGroupCode"/>
 *         <element name="sizeSystem" type="{}SizeSystemCode"/>
 *         <element name="sizeType" type="{}SizeTypeCode"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "SizeDetails",
    propOrder = {"sizeDimension", "sizeGroup", "sizeSystem", "sizeType"})
public class SizeDetailsXMLImpl implements SizeDetails<QuantitativeValueXMLImpl> {

  @XmlElement(required = true)
  protected QuantitativeValueXMLImpl sizeDimension;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected SizeGroupCode sizeGroup;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected SizeSystemCode sizeSystem;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected SizeTypeCode sizeType;

  /**
   * Gets the value of the sizeDimension property.
   *
   * @return possible object is {@link QuantitativeValueXMLImpl }
   */
  @Override
  public QuantitativeValueXMLImpl getSizeDimension() {
    return sizeDimension;
  }

  /**
   * Sets the value of the sizeDimension property.
   *
   * @param value allowed object is {@link QuantitativeValueXMLImpl }
   */
  @Override
  public void setSizeDimension(QuantitativeValueXMLImpl value) {
    this.sizeDimension = value;
  }

  /**
   * Gets the value of the sizeGroup property.
   *
   * @return possible object is {@link SizeGroupCode }
   */
  @Override
  public SizeGroupCode getSizeGroup() {
    return sizeGroup;
  }

  /**
   * Sets the value of the sizeGroup property.
   *
   * @param value allowed object is {@link SizeGroupCode }
   */
  @Override
  public void setSizeGroup(SizeGroupCode value) {
    this.sizeGroup = value;
  }

  /**
   * Gets the value of the sizeSystem property.
   *
   * @return possible object is {@link SizeSystemCode }
   */
  @Override
  public SizeSystemCode getSizeSystem() {
    return sizeSystem;
  }

  /**
   * Sets the value of the sizeSystem property.
   *
   * @param value allowed object is {@link SizeSystemCode }
   */
  @Override
  public void setSizeSystem(SizeSystemCode value) {
    this.sizeSystem = value;
  }

  /**
   * Gets the value of the sizeType property.
   *
   * @return possible object is {@link SizeTypeCode }
   */
  @Override
  public SizeTypeCode getSizeType() {
    return sizeType;
  }

  /**
   * Sets the value of the sizeType property.
   *
   * @param value allowed object is {@link SizeTypeCode }
   */
  @Override
  public void setSizeType(SizeTypeCode value) {
    this.sizeType = value;
  }
}
