//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for SizeTypeCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="SizeTypeCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="BACK"/>
 *     <enumeration value="CHEST_BUST"/>
 *     <enumeration value="COLLAR"/>
 *     <enumeration value="CUP"/>
 *     <enumeration value="HIPS"/>
 *     <enumeration value="INSEAM"/>
 *     <enumeration value="LENGTH"/>
 *     <enumeration value="ONE_DIMENSION"/>
 *     <enumeration value="OUTSIDE_LEG"/>
 *     <enumeration value="SLEEVE"/>
 *     <enumeration value="WAIST"/>
 *     <enumeration value="WIDTH"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "SizeTypeCode")
@XmlEnum
public enum SizeTypeCode {
  BACK,
  CHEST_BUST,
  COLLAR,
  CUP,
  HIPS,
  INSEAM,
  LENGTH,
  ONE_DIMENSION,
  OUTSIDE_LEG,
  SLEEVE,
  WAIST,
  WIDTH;

  public String value() {
    return name();
  }

  public static SizeTypeCode fromValue(String v) {
    return valueOf(v);
  }
}
