/*
 * Copyright 2022-2026 benelog GmbH & Co. KG
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for SourceAnimalCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="SourceAnimalCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="ALLIGATOR"/>
 *     <enumeration value="ASS"/>
 *     <enumeration value="BEAR"/>
 *     <enumeration value="BEEF_COW"/>
 *     <enumeration value="BOAR"/>
 *     <enumeration value="BUFFALO"/>
 *     <enumeration value="CALF"/>
 *     <enumeration value="CAMEL"/>
 *     <enumeration value="CHICKEN"/>
 *     <enumeration value="COCKEREL"/>
 *     <enumeration value="COW"/>
 *     <enumeration value="CROCODILE"/>
 *     <enumeration value="DEER"/>
 *     <enumeration value="DOG"/>
 *     <enumeration value="DUCK"/>
 *     <enumeration value="DUCKLING"/>
 *     <enumeration value="FISH"/>
 *     <enumeration value="FOWL"/>
 *     <enumeration value="FROG"/>
 *     <enumeration value="GOAT"/>
 *     <enumeration value="GOOSE"/>
 *     <enumeration value="GROUSE"/>
 *     <enumeration value="GUINEAFOWL"/>
 *     <enumeration value="HARE"/>
 *     <enumeration value="HORSE"/>
 *     <enumeration value="INVERTEBRATE"/>
 *     <enumeration value="LAMB"/>
 *     <enumeration value="LAND_SNAIL"/>
 *     <enumeration value="MILK_COW"/>
 *     <enumeration value="MOOSE"/>
 *     <enumeration value="OSTRICH"/>
 *     <enumeration value="OTHER"/>
 *     <enumeration value="PARTRIDGE"/>
 *     <enumeration value="PHEASANT"/>
 *     <enumeration value="PIGEON"/>
 *     <enumeration value="PORK"/>
 *     <enumeration value="POUSSIN"/>
 *     <enumeration value="QUAIL"/>
 *     <enumeration value="RABBIT"/>
 *     <enumeration value="RAT"/>
 *     <enumeration value="REINDEER"/>
 *     <enumeration value="ROE_DEER"/>
 *     <enumeration value="SHEEP"/>
 *     <enumeration value="SHELLFISH"/>
 *     <enumeration value="SNAKE"/>
 *     <enumeration value="SNIPE"/>
 *     <enumeration value="SPARROW"/>
 *     <enumeration value="THRUSH"/>
 *     <enumeration value="TURKEY"/>
 *     <enumeration value="TURTLE"/>
 *     <enumeration value="WOODCOCK"/>
 *     <enumeration value="YAK"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "SourceAnimalCode")
@XmlEnum
public enum SourceAnimalCode {
  ALLIGATOR,
  ASS,
  BEAR,
  BEEF_COW,
  BOAR,
  BUFFALO,
  CALF,
  CAMEL,
  CHICKEN,
  COCKEREL,
  COW,
  CROCODILE,
  DEER,
  DOG,
  DUCK,
  DUCKLING,
  FISH,
  FOWL,
  FROG,
  GOAT,
  GOOSE,
  GROUSE,
  GUINEAFOWL,
  HARE,
  HORSE,
  INVERTEBRATE,
  LAMB,
  LAND_SNAIL,
  MILK_COW,
  MOOSE,
  OSTRICH,
  OTHER,
  PARTRIDGE,
  PHEASANT,
  PIGEON,
  PORK,
  POUSSIN,
  QUAIL,
  RABBIT,
  RAT,
  REINDEER,
  ROE_DEER,
  SHEEP,
  SHELLFISH,
  SNAKE,
  SNIPE,
  SPARROW,
  THRUSH,
  TURKEY,
  TURTLE,
  WOODCOCK,
  YAK;

  public String value() {
    return name();
  }

  public static SourceAnimalCode fromValue(String v) {
    return valueOf(v);
  }
}
