/*
 * Copyright 2022-2026 benelog GmbH & Co. KG
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.TextileMaterialDetails;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.LinkedHashMap;

/**
 * Details on the composition of any materials used to make a product using textiles.
 *
 * <p>Java class for TextileMaterialDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="TextileMaterialDetails">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="textileMaterialDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="textileMaterialPercentage" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         <element name="textileMaterialThreadCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="textileMaterialWeight" type="{}QuantitativeValue"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
        name = "TextileMaterialDetails",
        propOrder = {
                "textileMaterialDescription",
                "textileMaterialPercentage",
                "textileMaterialThreadCount",
                "textileMaterialWeight"
        })
public class TextileMaterialDetailsXMLImpl implements TextileMaterialDetails<QuantitativeValueXMLImpl> {

    @XmlElement(required = true)
    protected LinkedHashMap<String, String> textileMaterialDescription;

    protected float textileMaterialPercentage;

    @XmlElement(required = true)
    protected LinkedHashMap<String, String> textileMaterialThreadCount;

    @XmlElement(required = true)
    protected QuantitativeValueXMLImpl textileMaterialWeight;

    /**
     * Gets the value of the textileMaterialDescription property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public LinkedHashMap<String, String> getTextileMaterialDescription() {
        if (textileMaterialDescription == null) {
            textileMaterialDescription = new LinkedHashMap<>();
        }
        return textileMaterialDescription;
    }

    /**
     * Sets the value of the textileMaterialDescription property.
     *
     * @param value allowed object is {@link String }
     */
    @Override
    public void setTextileMaterialDescription(LinkedHashMap<String, String> value) {
        this.textileMaterialDescription = value;
    }

    /**
     * Gets the value of the textileMaterialPercentage property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public float getTextileMaterialPercentage() {
        return textileMaterialPercentage;
    }

    /**
     * Sets the value of the textileMaterialPercentage property.
     *
     * @param value allowed object is {@link String }
     */
    @Override
    public void setTextileMaterialPercentage(float value) {
        this.textileMaterialPercentage = value;
    }

    /**
     * Gets the value of the textileMaterialThreadCount property.
     *
     * @return possible object is {@link String }
     */
    @Override
    public LinkedHashMap<String, String> getTextileMaterialThreadCount() {
        if (textileMaterialThreadCount == null) {
            textileMaterialThreadCount = new LinkedHashMap<>();
        }
        return textileMaterialThreadCount;
    }

    /**
     * Sets the value of the textileMaterialThreadCount property.
     *
     * @param value allowed object is {@link String }
     */
    @Override
    public void setTextileMaterialThreadCount(LinkedHashMap<String, String> value) {
        this.textileMaterialThreadCount = value;
    }

    /**
     * Gets the value of the textileMaterialWeight property.
     *
     * @return possible object is {@link QuantitativeValueXMLImpl }
     */
    @Override
    public QuantitativeValueXMLImpl getTextileMaterialWeight() {
        return textileMaterialWeight;
    }

    /**
     * Sets the value of the textileMaterialWeight property.
     *
     * @param value allowed object is {@link QuantitativeValueXMLImpl }
     */
    @Override
    public void setTextileMaterialWeight(QuantitativeValueXMLImpl value) {
        this.textileMaterialWeight = value;
    }
}
