//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import io.openepcis.model.interfaces.TypeCode;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for TypeCode complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <complexType name="TypeCode">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="originalCodeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "TypeCode",
    propOrder = {"originalCodeValue"})
public class TypeCodeXMLImpl implements TypeCode {

  @XmlElement(required = true)
  protected String originalCodeValue;

  /**
   * Gets the value of the originalCodeValue property.
   *
   * @return possible object is {@link String }
   */
  @Override
  public String getOriginalCodeValue() {
    return originalCodeValue;
  }

  /**
   * Sets the value of the originalCodeValue property.
   *
   * @param value allowed object is {@link String }
   */
  @Override
  public void setOriginalCodeValue(String value) {
    this.originalCodeValue = value;
  }
}
