//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
//

package io.openepcis.model.gs1webvocab;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;

/**
 * Java class for UpperTypeCode.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>{@code
 * <simpleType name="UpperTypeCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CLOSED_TOE_CLOSED_BACK_OPEN_INSTEP"/>
 *     <enumeration value="CLOSED_TOE_OPEN_BACK"/>
 *     <enumeration value="CLOSED_TOE_STRAP_BACK"/>
 *     <enumeration value="FULLY_CLOSED"/>
 *     <enumeration value="OPEN_TOE_FULLY_CLOSED_BACK"/>
 *     <enumeration value="OPEN_TOE_OPEN_BACK"/>
 *     <enumeration value="OPEN_TOE_STRAP_BACK"/>
 *     <enumeration value="UNCLASSIFIED"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 */
@XmlType(name = "UpperTypeCode")
@XmlEnum
public enum UpperTypeCode {
  CLOSED_TOE_CLOSED_BACK_OPEN_INSTEP,
  CLOSED_TOE_OPEN_BACK,
  CLOSED_TOE_STRAP_BACK,
  FULLY_CLOSED,
  OPEN_TOE_FULLY_CLOSED_BACK,
  OPEN_TOE_OPEN_BACK,
  OPEN_TOE_STRAP_BACK,
  UNCLASSIFIED;

  public String value() {
    return name();
  }

  public static UpperTypeCode fromValue(String v) {
    return valueOf(v);
  }
}
